TARGET = tnt

SOURCES = tnt.c ridetrack.c setpoint.c foc_tone.c runtime.c remote_input.c surge.c kalman.c traction.c pid.c biquad.c motor_data_tnt.c footpad_sensor.c state_tnt.c utils_tnt.c conf/buffer.c conf/confparser.c conf/confxml.c

USE_STLIB = yes
VESC_C_LIB_PATH = ../../c_libs/
include $(VESC_C_LIB_PATH)rules.mk
