TARGET = tnt

SOURCES = tnt.c proportional_gain.c biquad.c motor_data.c footpad_sensor.c state.c utils.c conf/buffer.c conf/confparser.c conf/confxml.c

USE_STLIB = yes
VESC_C_LIB_PATH = ../../c_libs/
include $(VESC_C_LIB_PATH)rules.mk
