TARGET = tnt

SOURCES = tnt.c yaw_gain.c drop.c remote_input.c ride_time.c high_current.c kalman.c traction.c proportional_gain.c biquad.c motor_data_tnt.c footpad_sensor.c state_tnt.c utils_tnt.c conf/buffer.c conf/confparser.c conf/confxml.c

USE_STLIB = yes
VESC_C_LIB_PATH = ../../c_libs/
include $(VESC_C_LIB_PATH)rules.mk
