#!/bin/bash

VT=/usr/local/bin/vesc_tool

set -e

# Build all packages here. Note:
# the buildPkg flag has an argument with 4 or 6 comma-separated flags. When
# 4 flags are used the description and name is taken from the existing VESC
# package. When 6 flags are used a markdown-file and a package name can be
# passed. When using 4 flags a package-file must exist beforehand (e.g. by
# creating it from the editor in VESC tool).

# Balance
cd balance/balance/
make clean
make
cd ../
$VT --buildPkg 'balance.vescpkg:balance.lisp:ui.qml:0:README.md:Balance'
cd balance
make clean
cd ../../

# Float
cd float/float/
make clean
make
cd ../
cp README.md READMEx.md
echo "- Version: v" >> READMEx.md
truncate -s-1 READMEx.md
cd float/conf
# Get version number out of settings.xml - assumes that valDouble is exactly 8 lines after the parameter name:
LINENUMBER=$(grep -n APPCONF_FLOAT_VERSION settings.xml | tr -dc '0-9')
head -$(($LINENUMBER + 8)) settings.xml | tail -1 | tr -dc '[.[:digit:]]' >> ../../READMEx.md
cd ../..
echo "" >> READMEx.md
echo "- Build Date: " >> READMEx.md
truncate -s-1 READMEx.md
date +'%D %T' >> READMEx.md
echo "- Git Commit: #" >> READMEx.md
truncate -s-1 READMEx.md
git rev-parse --short HEAD >> READMEx.md
$VT --buildPkg 'float.vescpkg:float.lisp:ui.qml:0:READMEx.md:Float'
rm READMEx.md
cd float
make clean
cd ../../

# logui
cd logui/
$VT --buildPkg 'logui.vescpkg:logger.lisp:ui.qml:0:README.md:LogUI'
cd ../

## Libraries

# WS2812
cd lib_ws2812/ws2812/
make clean
make
cd ../
$VT --buildPkg 'ws2812.vescpkg:ws2812.lisp::0'
cd ws2812
make clean
cd ../../

# NAU7802
cd lib_nau7802/
$VT --buildPkg 'nau7802.vescpkg:nau7802.lisp::0'
cd ../

# Interpolation
cd lib_interpolation/interpolation/
make clean
make
cd ../
$VT --buildPkg 'interpolation.vescpkg:interpolation.lisp::0:README.md:Interpolation'
cd interpolation
make clean
cd ../../

# Files
cd lib_files/
$VT --buildPkg 'files.vescpkg:files.lisp::0:README.md:Files'
cd ../

# PN532
cd lib_pn532/
$VT --buildPkg 'pn532.vescpkg:pn532.lisp::0:README.md:PN532'
cd ../

rcc -binary res_all.qrc -o vesc_pkg_all.rcc

