// This file is autogenerated by VESC Tool

#ifndef CONF_DEFAULT_H_
#define CONF_DEFAULT_H_

// Pitch Kp0
#ifndef APPCONF_TNT_KP0
#define APPCONF_TNT_KP0 0
#endif

// Pitch 1 Current
#ifndef APPCONF_TNT_CURRENT1
#define APPCONF_TNT_CURRENT1 1
#endif

// Pitch 2 Current
#ifndef APPCONF_TNT_CURRENT2
#define APPCONF_TNT_CURRENT2 5
#endif

// Pitch 3 Current
#ifndef APPCONF_TNT_CURRENT3
#define APPCONF_TNT_CURRENT3 140
#endif

// Pitch 4 Current
#ifndef APPCONF_TNT_CURRENT4
#define APPCONF_TNT_CURRENT4 0
#endif

// Pitch 5 Current
#ifndef APPCONF_TNT_CURRENT5
#define APPCONF_TNT_CURRENT5 0
#endif

// Pitch 6 Current
#ifndef APPCONF_TNT_CURRENT6
#define APPCONF_TNT_CURRENT6 0
#endif

// Pitch 1
#ifndef APPCONF_TNT_PITCH1
#define APPCONF_TNT_PITCH1 0.3
#endif

// Pitch 2
#ifndef APPCONF_TNT_PITCH2
#define APPCONF_TNT_PITCH2 0.7
#endif

// Pitch 3
#ifndef APPCONF_TNT_PITCH3
#define APPCONF_TNT_PITCH3 3
#endif

// Pitch 4
#ifndef APPCONF_TNT_PITCH4
#define APPCONF_TNT_PITCH4 4
#endif

// Pitch 5
#ifndef APPCONF_TNT_PITCH5
#define APPCONF_TNT_PITCH5 5
#endif

// Pitch 6
#ifndef APPCONF_TNT_PITCH6
#define APPCONF_TNT_PITCH6 5
#endif

// Enable Pitch Kp Input
#ifndef APPCONF_TNT_PITCH_KP_INPUT
#define APPCONF_TNT_PITCH_KP_INPUT 0
#endif

// Mahony KP
#ifndef APPCONF_TNT_MAHONY_KP
#define APPCONF_TNT_MAHONY_KP 2
#endif

// Pitch Rate Kp
#ifndef APPCONF_TNT_KP_RATE
#define APPCONF_TNT_KP_RATE 0.45
#endif

// Pitch Filter
#ifndef APPCONF_TNT_PITCH_FILTER
#define APPCONF_TNT_PITCH_FILTER 25
#endif

// Kalman Factor 1
#ifndef APPCONF_TNT_KALMAN1
#define APPCONF_TNT_KALMAN1 10
#endif

// Kalman Factor 2
#ifndef APPCONF_TNT_KALMAN2
#define APPCONF_TNT_KALMAN2 0
#endif

// Kalman Factor 3
#ifndef APPCONF_TNT_KALMAN3
#define APPCONF_TNT_KALMAN3 0.5
#endif

// Enable Brake Curve
#ifndef APPCONF_TNT_BRAKE_CURVE
#define APPCONF_TNT_BRAKE_CURVE 0
#endif

// Pitch Kp0
#ifndef APPCONF_TNT_BRAKEKP0
#define APPCONF_TNT_BRAKEKP0 0
#endif

// Pitch Rate Kp
#ifndef APPCONF_TNT_BRAKEKP_RATE
#define APPCONF_TNT_BRAKEKP_RATE 0.45
#endif

// Pitch 1 Current
#ifndef APPCONF_TNT_BRAKECURRENT1
#define APPCONF_TNT_BRAKECURRENT1 1
#endif

// Pitch 2 Current
#ifndef APPCONF_TNT_BRAKECURRENT2
#define APPCONF_TNT_BRAKECURRENT2 5
#endif

// Pitch 3 Current
#ifndef APPCONF_TNT_BRAKECURRENT3
#define APPCONF_TNT_BRAKECURRENT3 140
#endif

// Pitch 4 Current
#ifndef APPCONF_TNT_BRAKECURRENT4
#define APPCONF_TNT_BRAKECURRENT4 0
#endif

// Pitch 5 Current
#ifndef APPCONF_TNT_BRAKECURRENT5
#define APPCONF_TNT_BRAKECURRENT5 0
#endif

// Pitch 6 Current
#ifndef APPCONF_TNT_BRAKECURRENT6
#define APPCONF_TNT_BRAKECURRENT6 0
#endif

// Pitch 1
#ifndef APPCONF_TNT_BRAKEPITCH1
#define APPCONF_TNT_BRAKEPITCH1 0.3
#endif

// Pitch 2
#ifndef APPCONF_TNT_BRAKEPITCH2
#define APPCONF_TNT_BRAKEPITCH2 0.7
#endif

// Pitch 3
#ifndef APPCONF_TNT_BRAKEPITCH3
#define APPCONF_TNT_BRAKEPITCH3 3
#endif

// Pitch 4
#ifndef APPCONF_TNT_BRAKEPITCH4
#define APPCONF_TNT_BRAKEPITCH4 4
#endif

// Pitch 5
#ifndef APPCONF_TNT_BRAKEPITCH5
#define APPCONF_TNT_BRAKEPITCH5 5
#endif

// Pitch 6
#ifndef APPCONF_TNT_BRAKEPITCH6
#define APPCONF_TNT_BRAKEPITCH6 6
#endif

// Enable Pitch Kp Input Braking
#ifndef APPCONF_TNT_PITCH_KP_INPUT_BRAKE
#define APPCONF_TNT_PITCH_KP_INPUT_BRAKE 0
#endif

// Level 1 Roll Kp
#ifndef APPCONF_TNT_ROLL_KP1
#define APPCONF_TNT_ROLL_KP1 0
#endif

// Level 2 Roll Kp
#ifndef APPCONF_TNT_ROLL_KP2
#define APPCONF_TNT_ROLL_KP2 0.3
#endif

// Level 3 Roll Kp
#ifndef APPCONF_TNT_ROLL_KP3
#define APPCONF_TNT_ROLL_KP3 0
#endif

// Level 1 Roll Angle
#ifndef APPCONF_TNT_ROLL1
#define APPCONF_TNT_ROLL1 5
#endif

// Level 2 Roll Angle
#ifndef APPCONF_TNT_ROLL2
#define APPCONF_TNT_ROLL2 35
#endif

// Level 3 Roll Angle
#ifndef APPCONF_TNT_ROLL3
#define APPCONF_TNT_ROLL3 0
#endif

// Level 1 Roll Kp Braking
#ifndef APPCONF_TNT_BRKROLL_KP1
#define APPCONF_TNT_BRKROLL_KP1 0
#endif

// Level 2 Roll Kp Braking
#ifndef APPCONF_TNT_BRKROLL_KP2
#define APPCONF_TNT_BRKROLL_KP2 0.3
#endif

// Level 3 Roll Kp Braking
#ifndef APPCONF_TNT_BRKROLL_KP3
#define APPCONF_TNT_BRKROLL_KP3 0
#endif

// Level 1 Roll Angle Braking
#ifndef APPCONF_TNT_BRKROLL1
#define APPCONF_TNT_BRKROLL1 5
#endif

// Level 2 Roll Angle Braking
#ifndef APPCONF_TNT_BRKROLL2
#define APPCONF_TNT_BRKROLL2 35
#endif

// Level 3 Roll Angle Braking
#ifndef APPCONF_TNT_BRKROLL3
#define APPCONF_TNT_BRKROLL3 0
#endif

// Roll High ERPM Scale
#ifndef APPCONF_TNT_ROLLKP_HIGHERPM
#define APPCONF_TNT_ROLLKP_HIGHERPM 2500
#endif

// Roll Low ERPM Scale
#ifndef APPCONF_TNT_ROLLKP_LOWERPM
#define APPCONF_TNT_ROLLKP_LOWERPM 750
#endif

// Roll Maximum Scaler
#ifndef APPCONF_TNT_ROLLKP_MAXSCALE
#define APPCONF_TNT_ROLLKP_MAXSCALE 500
#endif

// Level 1 Yaw Kp
#ifndef APPCONF_TNT_YAW_KP1
#define APPCONF_TNT_YAW_KP1 0
#endif

// Level 2 Yaw Kp
#ifndef APPCONF_TNT_YAW_KP2
#define APPCONF_TNT_YAW_KP2 0.1
#endif

// Level 3 Yaw Kp
#ifndef APPCONF_TNT_YAW_KP3
#define APPCONF_TNT_YAW_KP3 0
#endif

// Level 1 Yaw Angle Change
#ifndef APPCONF_TNT_YAW1
#define APPCONF_TNT_YAW1 120
#endif

// Level 2 Yaw Angle Change
#ifndef APPCONF_TNT_YAW2
#define APPCONF_TNT_YAW2 500
#endif

// Level 3 Yaw Angle Change
#ifndef APPCONF_TNT_YAW3
#define APPCONF_TNT_YAW3 750
#endif

// Level 1 Yaw Kp Braking
#ifndef APPCONF_TNT_BRKYAW_KP1
#define APPCONF_TNT_BRKYAW_KP1 0
#endif

// Level 2 Yaw Kp Braking
#ifndef APPCONF_TNT_BRKYAW_KP2
#define APPCONF_TNT_BRKYAW_KP2 0.08
#endif

// Level 3 Yaw Kp Braking
#ifndef APPCONF_TNT_BRKYAW_KP3
#define APPCONF_TNT_BRKYAW_KP3 0
#endif

// Level 1 Yaw Angle Braking
#ifndef APPCONF_TNT_BRKYAW1
#define APPCONF_TNT_BRKYAW1 120
#endif

// Level 2 Yaw Angle Braking
#ifndef APPCONF_TNT_BRKYAW2
#define APPCONF_TNT_BRKYAW2 500
#endif

// Level 3 Yaw Angle Braking
#ifndef APPCONF_TNT_BRKYAW3
#define APPCONF_TNT_BRKYAW3 750
#endif

// Yaw Minimum ERPM
#ifndef APPCONF_TNT_YAW_MINERPM
#define APPCONF_TNT_YAW_MINERPM 1500
#endif

// Enable Surge
#ifndef APPCONF_TNT_IS_SURGE_ENABLED
#define APPCONF_TNT_IS_SURGE_ENABLED 0
#endif

// High Current Threshold, Low Duty
#ifndef APPCONF_TNT_SURGE_STARTCURRENT
#define APPCONF_TNT_SURGE_STARTCURRENT 85
#endif

// High Current Threshold, Max Duty
#ifndef APPCONF_TNT_SURGE_START_HD_CURRENT
#define APPCONF_TNT_SURGE_START_HD_CURRENT 30
#endif

// Duty to Start Current Scaling
#ifndef APPCONF_TNT_SURGE_SCALEDUTY
#define APPCONF_TNT_SURGE_SCALEDUTY 35
#endif

// Surge Setpoint Margin
#ifndef APPCONF_TNT_SURGE_PITCHMARGIN
#define APPCONF_TNT_SURGE_PITCHMARGIN 3
#endif

// Surge Max Nose Lift
#ifndef APPCONF_TNT_SURGE_MAXANGLE
#define APPCONF_TNT_SURGE_MAXANGLE 2
#endif

// High Current Minimum ERPM
#ifndef APPCONF_TNT_SURGE_MINERPM
#define APPCONF_TNT_SURGE_MINERPM 1500
#endif

// Surge Max Ramp Rate
#ifndef APPCONF_TNT_SURGE_DUTY
#define APPCONF_TNT_SURGE_DUTY 150
#endif

// Surge Return Speed
#ifndef APPCONF_TNT_TILTBACK_SURGE_SPEED
#define APPCONF_TNT_TILTBACK_SURGE_SPEED 20
#endif

// Enable Traction Control
#ifndef APPCONF_TNT_IS_TRACTION_ENABLED
#define APPCONF_TNT_IS_TRACTION_ENABLED 1
#endif

// End Condition
#ifndef APPCONF_TNT_WHEELSLIP_MARGIN
#define APPCONF_TNT_WHEELSLIP_MARGIN 2
#endif

// Start Condition
#ifndef APPCONF_TNT_WHEELSLIP_ACCELSTART
#define APPCONF_TNT_WHEELSLIP_ACCELSTART 29
#endif

// Transition Condition
#ifndef APPCONF_TNT_WHEELSLIP_ACCELEND
#define APPCONF_TNT_WHEELSLIP_ACCELEND 4
#endif

// Low ERPM Scaler
#ifndef APPCONF_TNT_WHEELSLIP_SCALEACCEL
#define APPCONF_TNT_WHEELSLIP_SCALEACCEL 5
#endif

// Scale ERPM
#ifndef APPCONF_TNT_WHEELSLIP_SCALEERPM
#define APPCONF_TNT_WHEELSLIP_SCALEERPM 3000
#endif

// Enable Traction Braking
#ifndef APPCONF_TNT_IS_TRACTION_BRAKING_ENABLED
#define APPCONF_TNT_IS_TRACTION_BRAKING_ENABLED 0
#endif

// Input Tilt Angle
#ifndef APPCONF_TNT_TRACTION_BRAKING_ANGLE
#define APPCONF_TNT_TRACTION_BRAKING_ANGLE 6
#endif

// Enable Speed Stability
#ifndef APPCONF_TNT_ENABLE_SPEED_STABILITY
#define APPCONF_TNT_ENABLE_SPEED_STABILITY 1
#endif

// Enable Throttle Stability
#ifndef APPCONF_TNT_ENABLE_THROTTLE_STABILITY
#define APPCONF_TNT_ENABLE_THROTTLE_STABILITY 0
#endif

// Pitch Current Max Stability
#ifndef APPCONF_TNT_STABL_PITCH_MAXSCALE
#define APPCONF_TNT_STABL_PITCH_MAXSCALE 50
#endif

// Pitch Rate Max Stability
#ifndef APPCONF_TNT_STABL_RATE_MAXSCALE
#define APPCONF_TNT_STABL_RATE_MAXSCALE 100
#endif

// Minimum Scale ERPM
#ifndef APPCONF_TNT_STABL_MIN_ERPM
#define APPCONF_TNT_STABL_MIN_ERPM 3000
#endif

// Maximum Scale ERPM
#ifndef APPCONF_TNT_STABL_MAX_ERPM
#define APPCONF_TNT_STABL_MAX_ERPM 8000
#endif

// Ramp Rate Up
#ifndef APPCONF_TNT_STABL_RAMP
#define APPCONF_TNT_STABL_RAMP 25
#endif

// Ramp Rate Down
#ifndef APPCONF_TNT_STABL_RAMP_DOWN
#define APPCONF_TNT_STABL_RAMP_DOWN 5
#endif

// Loop Hertz
#ifndef APPCONF_TNT_HERTZ
#define APPCONF_TNT_HERTZ 832
#endif

// Pitch Axis Fault Cutoff
#ifndef APPCONF_TNT_FAULT_PITCH
#define APPCONF_TNT_FAULT_PITCH 80
#endif

// Roll Axis Fault Cutoff
#ifndef APPCONF_TNT_FAULT_ROLL
#define APPCONF_TNT_FAULT_ROLL 80
#endif

// ADC1 Switch Voltage
#ifndef APPCONF_TNT_FAULT_ADC1
#define APPCONF_TNT_FAULT_ADC1 2.5
#endif

// ADC2 Switch Voltage
#ifndef APPCONF_TNT_FAULT_ADC1
#define APPCONF_TNT_FAULT_ADC1 2.5
#endif

// Beep on Sensor Fault
#ifndef APPCONF_TNT_IS_FOOTBEEP_ENABLED
#define APPCONF_TNT_IS_FOOTBEEP_ENABLED 1
#endif

// Angle Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_PITCH
#define APPCONF_TNT_FAULT_DELAY_PITCH 250
#endif

// Half Switch Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_SWITCH_HALF
#define APPCONF_TNT_FAULT_DELAY_SWITCH_HALF 500
#endif

// Full Switch Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_SWITCH_FULL
#define APPCONF_TNT_FAULT_DELAY_SWITCH_FULL 250
#endif

// ADC Half State Fault ERPM
#ifndef APPCONF_TNT_FAULT_ADC_HALF_ERPM
#define APPCONF_TNT_FAULT_ADC_HALF_ERPM 200
#endif

// Treat Both Sensors as One (Posi)
#ifndef APPCONF_TNT_FAULT_IS_DUAL_SWITCH
#define APPCONF_TNT_FAULT_IS_DUAL_SWITCH 0
#endif

// Disable Moving Faults
#ifndef APPCONF_TNT_FAULT_MOVING_FAULT_DISABLED
#define APPCONF_TNT_FAULT_MOVING_FAULT_DISABLED 0
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_DUTY_ANGLE
#define APPCONF_TNT_TILTBACK_DUTY_ANGLE 5
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_DUTY_SPEED
#define APPCONF_TNT_TILTBACK_DUTY_SPEED 3
#endif

// Duty Cycle
#ifndef APPCONF_TNT_TILTBACK_DUTY
#define APPCONF_TNT_TILTBACK_DUTY 80
#endif

// Beep on Duty Tiltback
#ifndef APPCONF_TNT_IS_DUTYBEEP_ENABLED
#define APPCONF_TNT_IS_DUTYBEEP_ENABLED 0
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_HV_ANGLE
#define APPCONF_TNT_TILTBACK_HV_ANGLE 8
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_HV_SPEED
#define APPCONF_TNT_TILTBACK_HV_SPEED 1
#endif

// High Voltage Threshold
#ifndef APPCONF_TNT_TILTBACK_HV
#define APPCONF_TNT_TILTBACK_HV 84.5
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_LV_ANGLE
#define APPCONF_TNT_TILTBACK_LV_ANGLE 8
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_LV_SPEED
#define APPCONF_TNT_TILTBACK_LV_SPEED 1
#endif

// Low Voltage Threshold
#ifndef APPCONF_TNT_TILTBACK_LV
#define APPCONF_TNT_TILTBACK_LV 60
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_HT_ANGLE
#define APPCONF_TNT_TILTBACK_HT_ANGLE 8
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_HT_SPEED
#define APPCONF_TNT_TILTBACK_HT_SPEED 1
#endif

// Return To Level Speed
#ifndef APPCONF_TNT_TILTBACK_RETURN_SPEED
#define APPCONF_TNT_TILTBACK_RETURN_SPEED 5
#endif

// Constant Tiltback
#ifndef APPCONF_TNT_TILTBACK_CONSTANT
#define APPCONF_TNT_TILTBACK_CONSTANT 0
#endif

// Constant Tiltback ERPM
#ifndef APPCONF_TNT_TILTBACK_CONSTANT_ERPM
#define APPCONF_TNT_TILTBACK_CONSTANT_ERPM 500
#endif

// Haptic Buzz Maximum Intensity
#ifndef APPCONF_TNT_HAPTIC_BUZZ_INTENSITY
#define APPCONF_TNT_HAPTIC_BUZZ_INTENSITY 12
#endif

// Haptic Buzz Minimum Intensity
#ifndef APPCONF_TNT_HAPTIC_BUZZ_MIN
#define APPCONF_TNT_HAPTIC_BUZZ_MIN 10
#endif

// Enable High Current Haptic Buzz
#ifndef APPCONF_TNT_HAPTIC_BUZZ_CURRENT
#define APPCONF_TNT_HAPTIC_BUZZ_CURRENT 1
#endif

// Enable High Duty Haptic Buzz
#ifndef APPCONF_TNT_HAPTIC_BUZZ_DUTY
#define APPCONF_TNT_HAPTIC_BUZZ_DUTY 1
#endif

// Nose Angling Speed
#ifndef APPCONF_TNT_NOSEANGLING_SPEED
#define APPCONF_TNT_NOSEANGLING_SPEED 5
#endif

// Remote Type
#ifndef APPCONF_TNT_INPUTTILT_REMOTE_TYPE
#define APPCONF_TNT_INPUTTILT_REMOTE_TYPE 2
#endif

// Tiltback Angle Limit
#ifndef APPCONF_TNT_INPUTTILT_ANGLE_LIMIT
#define APPCONF_TNT_INPUTTILT_ANGLE_LIMIT 12
#endif

// Tiltback Speed
#ifndef APPCONF_TNT_INPUTTILT_SPEED
#define APPCONF_TNT_INPUTTILT_SPEED 40
#endif

// Tiltback Smoothing Factor
#ifndef APPCONF_TNT_INPUTTILT_SMOOTHING_FACTOR
#define APPCONF_TNT_INPUTTILT_SMOOTHING_FACTOR 1
#endif

// Invert Throttle
#ifndef APPCONF_TNT_INPUTTILT_INVERT_THROTTLE
#define APPCONF_TNT_INPUTTILT_INVERT_THROTTLE 0
#endif

// Input Deadband
#ifndef APPCONF_TNT_INPUTTILT_DEADBAND
#define APPCONF_TNT_INPUTTILT_DEADBAND 0.05
#endif

// Sticky Tilt Angle 1
#ifndef APPCONF_TNT_STICKYTILT_VAL1
#define APPCONF_TNT_STICKYTILT_VAL1 3
#endif

// Sticky Tilt Angle 2
#ifndef APPCONF_TNT_STICKYTILT_VAL2
#define APPCONF_TNT_STICKYTILT_VAL2 6
#endif

// Sticky Tilt Hold Current
#ifndef APPCONF_TNT_STICKYTILT_HOLDCURRENT
#define APPCONF_TNT_STICKYTILT_HOLDCURRENT 20
#endif

// Enable Stickytilt
#ifndef APPCONF_TNT_IS_STICKYTILT_ENABLED
#define APPCONF_TNT_IS_STICKYTILT_ENABLED 1
#endif

// Startup Pitch Axis Angle Tolerance
#ifndef APPCONF_TNT_STARTUP_PITCH_TOLERANCE
#define APPCONF_TNT_STARTUP_PITCH_TOLERANCE 7
#endif

// Startup Centering Speed
#ifndef APPCONF_TNT_STARTUP_SPEED
#define APPCONF_TNT_STARTUP_SPEED 60
#endif

// Enable Simple Start
#ifndef APPCONF_SIMPLESTART_ENABLED
#define APPCONF_SIMPLESTART_ENABLED 1
#endif

// Enable Push Start
#ifndef APPCONF_PUSHSTART_ENABLED
#define APPCONF_PUSHSTART_ENABLED 0
#endif

// Enable Dirty Landings
#ifndef APPCONF_DIRTYLANDINGS_ENABLED
#define APPCONF_DIRTYLANDINGS_ENABLED 0
#endif

// Brake Current
#ifndef APPCONF_TNT_BRAKE_CURRENT
#define APPCONF_TNT_BRAKE_CURRENT 6
#endif

// Haptic Buzz Current Margin
#ifndef APPCONF_TNT_OVERCURRENT_MARGIN
#define APPCONF_TNT_OVERCURRENT_MARGIN 10
#endif

// High Current Haptic Buzz Time
#ifndef APPCONF_TNT_OVERCURRENT_PERIOD
#define APPCONF_TNT_OVERCURRENT_PERIOD 0.3
#endif

// Enable Beeper on Servo/PPM
#ifndef APPCONF_TNT_IS_BEEPER_ENABLED
#define APPCONF_TNT_IS_BEEPER_ENABLED 0
#endif

// Enable Surge Debug Info
#ifndef APPCONF_TNT_IS_SURGEDEBUG_ENABLED
#define APPCONF_TNT_IS_SURGEDEBUG_ENABLED 0
#endif

// Enable Traction Control Debug Info
#ifndef APPCONF_TNT_IS_TCDEBUG_ENABLED
#define APPCONF_TNT_IS_TCDEBUG_ENABLED 1
#endif

// Enable Tune Debug Info
#ifndef APPCONF_TNT_IS_TRIPDEBUG_ENABLED
#define APPCONF_TNT_IS_TRIPDEBUG_ENABLED 0
#endif

// Enable Yaw Debug Info
#ifndef APPCONF_TNT_IS_YAWDEBUG_ENABLED
#define APPCONF_TNT_IS_YAWDEBUG_ENABLED 0
#endif

// Disable Package
#ifndef APPCONF_TNT_DISABLE
#define APPCONF_TNT_DISABLE 0
#endif

// Package Version
#ifndef APPCONF_TNT_VERSION
#define APPCONF_TNT_VERSION 1.3
#endif

// CONF_DEFAULT_H_
#endif

