// This file is autogenerated by VESC Tool

#ifndef CONF_DEFAULT_H_
#define CONF_DEFAULT_H_

// Pitch Kp0
#ifndef APPCONF_TNT_KP0
#define APPCONF_TNT_KP0 0
#endif

// Pitch 1 Current
#ifndef APPCONF_TNT_CURRENT1
#define APPCONF_TNT_CURRENT1 1
#endif

// Pitch 2 Current
#ifndef APPCONF_TNT_CURRENT2
#define APPCONF_TNT_CURRENT2 5
#endif

// Pitch 3 Current
#ifndef APPCONF_TNT_CURRENT3
#define APPCONF_TNT_CURRENT3 140
#endif

// Pitch 4 Current
#ifndef APPCONF_TNT_CURRENT4
#define APPCONF_TNT_CURRENT4 0
#endif

// Pitch 5 Current
#ifndef APPCONF_TNT_CURRENT5
#define APPCONF_TNT_CURRENT5 0
#endif

// Pitch 6 Current
#ifndef APPCONF_TNT_CURRENT6
#define APPCONF_TNT_CURRENT6 0
#endif

// Pitch 1
#ifndef APPCONF_TNT_PITCH1
#define APPCONF_TNT_PITCH1 0.2
#endif

// Pitch 2
#ifndef APPCONF_TNT_PITCH2
#define APPCONF_TNT_PITCH2 0.5
#endif

// Pitch 3
#ifndef APPCONF_TNT_PITCH3
#define APPCONF_TNT_PITCH3 3
#endif

// Pitch 4
#ifndef APPCONF_TNT_PITCH4
#define APPCONF_TNT_PITCH4 1.5
#endif

// Pitch 5
#ifndef APPCONF_TNT_PITCH5
#define APPCONF_TNT_PITCH5 2
#endif

// Pitch 6
#ifndef APPCONF_TNT_PITCH6
#define APPCONF_TNT_PITCH6 3
#endif

// Enable Pitch Kp Input
#ifndef APPCONF_TNT_PITCH_KP_INPUT
#define APPCONF_TNT_PITCH_KP_INPUT 0
#endif

// Mahony KP
#ifndef APPCONF_TNT_MAHONY_KP
#define APPCONF_TNT_MAHONY_KP 2
#endif

// Kp Rate
#ifndef APPCONF_TNT_KP_RATE
#define APPCONF_TNT_KP_RATE 0.4
#endif

// Pitch Filter
#ifndef APPCONF_TNT_PITCH_FILTER
#define APPCONF_TNT_PITCH_FILTER 25
#endif

// Kalman Factor 1
#ifndef APPCONF_TNT_KALMAN1
#define APPCONF_TNT_KALMAN1 10
#endif

// Kalman Factor 2
#ifndef APPCONF_TNT_KALMAN2
#define APPCONF_TNT_KALMAN2 0
#endif

// Kalman Factor 3
#ifndef APPCONF_TNT_KALMAN3
#define APPCONF_TNT_KALMAN3 0.5
#endif

// Level 1 Roll Kp
#ifndef APPCONF_TNT_ROLL_KP1
#define APPCONF_TNT_ROLL_KP1 0
#endif

// Level 2 Roll Kp
#ifndef APPCONF_TNT_ROLL_KP2
#define APPCONF_TNT_ROLL_KP2 0.3
#endif

// Level 3 Roll Kp
#ifndef APPCONF_TNT_ROLL_KP3
#define APPCONF_TNT_ROLL_KP3 0
#endif

// Level 1 Roll Angle
#ifndef APPCONF_TNT_ROLL1
#define APPCONF_TNT_ROLL1 5
#endif

// Level 2 Roll Angle
#ifndef APPCONF_TNT_ROLL2
#define APPCONF_TNT_ROLL2 25
#endif

// Level 3 Roll Angle
#ifndef APPCONF_TNT_ROLL3
#define APPCONF_TNT_ROLL3 0
#endif

// Level 1 Roll Kp Braking
#ifndef APPCONF_TNT_BRKROLL_KP1
#define APPCONF_TNT_BRKROLL_KP1 0
#endif

// Level 2 Roll Kp Braking
#ifndef APPCONF_TNT_BRKROLL_KP2
#define APPCONF_TNT_BRKROLL_KP2 0.3
#endif

// Level 3 Roll Kp Braking
#ifndef APPCONF_TNT_BRKROLL_KP3
#define APPCONF_TNT_BRKROLL_KP3 0
#endif

// Level 1 Roll Angle Braking
#ifndef APPCONF_TNT_BRKROLL1
#define APPCONF_TNT_BRKROLL1 5
#endif

// Level 2 Roll Angle Braking
#ifndef APPCONF_TNT_BRKROLL2
#define APPCONF_TNT_BRKROLL2 25
#endif

// Level 3 Roll Angle Braking
#ifndef APPCONF_TNT_BRKROLL3
#define APPCONF_TNT_BRKROLL3 0
#endif

// Roll High ERPM Scale
#ifndef APPCONF_TNT_ROLLKP_HIGHERPM
#define APPCONF_TNT_ROLLKP_HIGHERPM 3000
#endif

// Roll Low ERPM Scale
#ifndef APPCONF_TNT_ROLLKP_LOWERPM
#define APPCONF_TNT_ROLLKP_LOWERPM 750
#endif

// Roll Maximum Scaler
#ifndef APPCONF_TNT_ROLLKP_MAXSCALE
#define APPCONF_TNT_ROLLKP_MAXSCALE 300
#endif

// Enable Surge
#ifndef APPCONF_TNT_IS_SURGE_ENABLED
#define APPCONF_TNT_IS_SURGE_ENABLED 0
#endif

// Surge Period
#ifndef APPCONF_TNT_SURGE_PERIOD
#define APPCONF_TNT_SURGE_PERIOD 0.7
#endif

// Surge Cycle
#ifndef APPCONF_TNT_SURGE_CYCLE
#define APPCONF_TNT_SURGE_CYCLE 0.3
#endif

// Surge Start Angle Speed
#ifndef APPCONF_TNT_SURGE_STARTANGLESPEED
#define APPCONF_TNT_SURGE_STARTANGLESPEED 50
#endif

// Surge Start Differential
#ifndef APPCONF_TNT_SURGE_DIFFLIMIT
#define APPCONF_TNT_SURGE_DIFFLIMIT 3.5
#endif

// Surge End Current Margin
#ifndef APPCONF_TNT_SURGE_CURRENTMARGIN
#define APPCONF_TNT_SURGE_CURRENTMARGIN 1.3
#endif

// Enable Traction Control
#ifndef APPCONF_TNT_IS_TRACTION_ENABLED
#define APPCONF_TNT_IS_TRACTION_ENABLED 0
#endif

// Wheelslip Margin
#ifndef APPCONF_TNT_WHEELSLIP_MARGIN
#define APPCONF_TNT_WHEELSLIP_MARGIN 6
#endif

// Wheelslip Acceleration Trigger
#ifndef APPCONF_TNT_WHEELSLIP_ACCELSTART
#define APPCONF_TNT_WHEELSLIP_ACCELSTART 35
#endif

// Wheelslip Acceleration End
#ifndef APPCONF_TNT_WHEELSLIP_ACCELEND
#define APPCONF_TNT_WHEELSLIP_ACCELEND 5
#endif

// Wheelslip Low ERPM Scaler
#ifndef APPCONF_TNT_WHEELSLIP_SCALEACCEL
#define APPCONF_TNT_WHEELSLIP_SCALEACCEL 5
#endif

// Wheelslip Scale ERPM
#ifndef APPCONF_TNT_WHEELSLIP_SCALEERPM
#define APPCONF_TNT_WHEELSLIP_SCALEERPM 3000
#endif

// Loop Hertz
#ifndef APPCONF_TNT_HERTZ
#define APPCONF_TNT_HERTZ 832
#endif

// Pitch Axis Fault Cutoff
#ifndef APPCONF_TNT_FAULT_PITCH
#define APPCONF_TNT_FAULT_PITCH 80
#endif

// Roll Axis Fault Cutoff
#ifndef APPCONF_TNT_FAULT_ROLL
#define APPCONF_TNT_FAULT_ROLL 80
#endif

// ADC1 Switch Voltage
#ifndef APPCONF_TNT_FAULT_ADC1
#define APPCONF_TNT_FAULT_ADC1 3
#endif

// ADC2 Switch Voltage
#ifndef APPCONF_TNT_FAULT_ADC2
#define APPCONF_TNT_FAULT_ADC2 3
#endif

// Beep on Sensor Fault
#ifndef APPCONF_TNT_IS_FOOTBUZZ_ENABLED
#define APPCONF_TNT_IS_FOOTBUZZ_ENABLED 0
#endif

// Pitch Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_PITCH
#define APPCONF_TNT_FAULT_DELAY_PITCH 250
#endif

// Roll Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_ROLL
#define APPCONF_TNT_FAULT_DELAY_ROLL 250
#endif

// Half Switch Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_SWITCH_HALF
#define APPCONF_TNT_FAULT_DELAY_SWITCH_HALF 500
#endif

// Full Switch Fault Delay
#ifndef APPCONF_TNT_FAULT_DELAY_SWITCH_FULL
#define APPCONF_TNT_FAULT_DELAY_SWITCH_FULL 250
#endif

// ADC Half State Fault ERPM
#ifndef APPCONF_TNT_FAULT_ADC_HALF_ERPM
#define APPCONF_TNT_FAULT_ADC_HALF_ERPM 200
#endif

// Treat Both Sensors as One (Posi)
#ifndef APPCONF_TNT_FAULT_IS_DUAL_SWITCH
#define APPCONF_TNT_FAULT_IS_DUAL_SWITCH 0
#endif

// Disable Moving Faults
#ifndef APPCONF_TNT_FAULT_MOVING_FAULT_DISABLED
#define APPCONF_TNT_FAULT_MOVING_FAULT_DISABLED 0
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_DUTY_ANGLE
#define APPCONF_TNT_TILTBACK_DUTY_ANGLE 5
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_DUTY_SPEED
#define APPCONF_TNT_TILTBACK_DUTY_SPEED 3
#endif

// Duty Cycle
#ifndef APPCONF_TNT_TILTBACK_DUTY
#define APPCONF_TNT_TILTBACK_DUTY 0.8
#endif

// Beep on Duty Tiltback
#ifndef APPCONF_TNT_IS_DUTYBUZZ_ENABLED
#define APPCONF_TNT_IS_DUTYBUZZ_ENABLED 0
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_HV_ANGLE
#define APPCONF_TNT_TILTBACK_HV_ANGLE 8
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_HV_SPEED
#define APPCONF_TNT_TILTBACK_HV_SPEED 1
#endif

// High Voltage Threshold
#ifndef APPCONF_TNT_TILTBACK_HV
#define APPCONF_TNT_TILTBACK_HV 63.5
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_LV_ANGLE
#define APPCONF_TNT_TILTBACK_LV_ANGLE 8
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_LV_SPEED
#define APPCONF_TNT_TILTBACK_LV_SPEED 1
#endif

// Low Voltage Threshold
#ifndef APPCONF_TNT_TILTBACK_LV
#define APPCONF_TNT_TILTBACK_LV 45
#endif

// Angle
#ifndef APPCONF_TNT_TILTBACK_HT_ANGLE
#define APPCONF_TNT_TILTBACK_HT_ANGLE 10
#endif

// Speed
#ifndef APPCONF_TNT_TILTBACK_HT_SPEED
#define APPCONF_TNT_TILTBACK_HT_SPEED 1
#endif

// Return To Level Speed
#ifndef APPCONF_TNT_TILTBACK_RETURN_SPEED
#define APPCONF_TNT_TILTBACK_RETURN_SPEED 5
#endif

// Constant Tiltback
#ifndef APPCONF_TNT_TILTBACK_CONSTANT
#define APPCONF_TNT_TILTBACK_CONSTANT 0
#endif

// Constant Tiltback ERPM
#ifndef APPCONF_TNT_TILTBACK_CONSTANT_ERPM
#define APPCONF_TNT_TILTBACK_CONSTANT_ERPM 500
#endif

// Nose Angling Speed
#ifndef APPCONF_TNT_NOSEANGLING_SPEED
#define APPCONF_TNT_NOSEANGLING_SPEED 5
#endif

// Remote Type
#ifndef APPCONF_TNT_INPUTTILT_REMOTE_TYPE
#define APPCONF_TNT_INPUTTILT_REMOTE_TYPE 0
#endif

// Tiltback Angle Limit
#ifndef APPCONF_TNT_INPUTTILT_ANGLE_LIMIT
#define APPCONF_TNT_INPUTTILT_ANGLE_LIMIT 12
#endif

// Tiltback Speed
#ifndef APPCONF_TNT_INPUTTILT_SPEED
#define APPCONF_TNT_INPUTTILT_SPEED 40
#endif

// Tiltback Smoothing Factor
#ifndef APPCONF_TNT_INPUTTILT_SMOOTHING_FACTOR
#define APPCONF_TNT_INPUTTILT_SMOOTHING_FACTOR 1
#endif

// Invert Throttle
#ifndef APPCONF_TNT_INPUTTILT_INVERT_THROTTLE
#define APPCONF_TNT_INPUTTILT_INVERT_THROTTLE 0
#endif

// Input Deadband
#ifndef APPCONF_TNT_INPUTTILT_DEADBAND
#define APPCONF_TNT_INPUTTILT_DEADBAND 0.05
#endif

// Sticky Tilt Angle 1
#ifndef APPCONF_TNT_STICKYTILT_VAL1
#define APPCONF_TNT_STICKYTILT_VAL1 3
#endif

// Sticky Tilt Angle 2
#ifndef APPCONF_TNT_STICKYTILT_VAL2
#define APPCONF_TNT_STICKYTILT_VAL2 6
#endif

// Sticky Tilt Hold Current
#ifndef APPCONF_TNT_STICKYTILT_HOLDCURRENT
#define APPCONF_TNT_STICKYTILT_HOLDCURRENT 20
#endif

// Enable Stickytilt
#ifndef APPCONF_TNT_IS_STICKYTILT_ENABLED
#define APPCONF_TNT_IS_STICKYTILT_ENABLED 1
#endif

// Startup Pitch Axis Angle Tolerance
#ifndef APPCONF_TNT_STARTUP_PITCH_TOLERANCE
#define APPCONF_TNT_STARTUP_PITCH_TOLERANCE 7
#endif

// Startup Roll Axis Angle Tolerance
#ifndef APPCONF_TNT_STARTUP_ROLL_TOLERANCE
#define APPCONF_TNT_STARTUP_ROLL_TOLERANCE 45
#endif

// Startup Centering Speed
#ifndef APPCONF_TNT_STARTUP_SPEED
#define APPCONF_TNT_STARTUP_SPEED 60
#endif

// Startup Click Current
#ifndef APPCONF_TNT_STARTUP_CLICK_CURRENT
#define APPCONF_TNT_STARTUP_CLICK_CURRENT 0
#endif

// Enable Simple Start
#ifndef APPCONF_SIMPLESTART_ENABLED
#define APPCONF_SIMPLESTART_ENABLED 1
#endif

// Enable Push Start
#ifndef APPCONF_PUSHSTART_ENABLED
#define APPCONF_PUSHSTART_ENABLED 0
#endif

// Enable Dirty Landings
#ifndef APPCONF_DIRTYLANDINGS_ENABLED
#define APPCONF_DIRTYLANDINGS_ENABLED 0
#endif

// Brake Current
#ifndef APPCONF_TNT_BRAKE_CURRENT
#define APPCONF_TNT_BRAKE_CURRENT 6
#endif

// Enable Buzzer on Servo/PPM
#ifndef APPCONF_TNT_IS_BUZZER_ENABLED
#define APPCONF_TNT_IS_BUZZER_ENABLED 0
#endif

// Disable Package
#ifndef APPCONF_TNT_DISABLE
#define APPCONF_TNT_DISABLE 0
#endif

// Package Version
#ifndef APPCONF_TNT_VERSION
#define APPCONF_TNT_VERSION 1
#endif

// CONF_DEFAULT_H_
#endif

