// This file is autogenerated by VESC Tool

#ifndef CONFXML_H_
#define CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_FLOAT_CONFIG__SIZE		9785

// Variables
extern uint8_t data_float_config_[];

// CONFXML_H_
#endif
