import QtQuick 2.15

// Package description, used by `vesc_tool --buildPkgFromDesc pkgdesc.qml`.
// This form (rather than the colon-separated --buildPkg string) is what makes
// isCompatible below available, so the package can declare which hardware it
// runs on.
Item {
    property string pkgName: "Float Accessories"
    // Generated by the Makefile: README.md plus a Build Info section with the
    // version, build date and git commit.
    property string pkgDescriptionMd: "README-gen.md"
    property string pkgLisp: "float_accessories.lisp"
    property string pkgQml: "ui.qml"
    property bool pkgQmlIsFullscreen: false
    property string pkgOutput: "float_accessories.vescpkg"

    function isCompatible (fwRxParams) {
        var hwType = fwRxParams.hwTypeStr().toLowerCase();
        return hwType === "custom module";
    }
}
