#!/usr/bin/env python3
"""Generate esp_led_defs.lisp from esp_led_strip/code.c.

The C source is the single source of truth for the esp_led effect / palette /
type / timing / turn-mode ids. This script mirrors them into lisp so consumers
(float_accessories, the test UI, ...) cannot drift from the firmware-facing
enums. Run `make defs` in this directory; the package build runs it too.

Sources parsed from code.c:
  - the FX_ / TYPE_ / TIMING_ / TURN_ enums (values follow C rules)
  - the palettes[] table, one PAL_<NAME> per row (id = row position + 1, see
    parse_palettes)
"""

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "esp_led_strip" / "code.c"
OUT = HERE / "esp_led_defs.lisp"

# Exported groups, in output order: (C prefix, section header).
GROUPS = [
    ("FX_",     "Effect ids"),
    ("PAL_",    "Palette ids (values for ext-esp_led-seg-pal / -pal)"),
    ("TYPE_",   "Pixel byte order (GRBW / RGBW are 4 bytes per pixel)"),
    ("TIMING_", "Wire timing presets"),
    ("TURN_",   "Turn-signal modes, carried in the FX-TURN level param"),
]


def strip_block_comments(text):
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def parse_enums(text):
    """{NAME: (value, comment)} for every member of every enum block."""
    out = {}
    for body in re.findall(r"\benum\b\s*\{(.*?)\}", text, flags=re.S):
        counter = 0
        for line in body.splitlines():
            code, _, comment = line.partition("//")
            code = strip_block_comments(code)
            members = [m for m in code.split(",") if m.strip()]
            for i, member in enumerate(members):
                m = re.match(r"\s*([A-Za-z_]\w*)\s*(?:=\s*([0-9a-fA-FxX]+))?\s*$",
                             member)
                if not m:
                    continue
                if m.group(2) is not None:
                    counter = int(m.group(2), 0)
                # A trailing // comment belongs to the last member on the line.
                tail = comment.strip() if i == len(members) - 1 else ""
                out[m.group(1)] = (counter, tail)
                counter += 1
    return out


def parse_palettes(text):
    """{PAL_NAME: (id, comment)} in array order.

    The ids are what ext-esp_led-seg-pal takes, NOT the raw row positions:
    seg_palette_at() reserves 0 for the segment's custom palette and maps
    1..N onto palettes[id - 1], so a row's id is its position + 1.
    """
    block = re.search(r"palettes\[\]\s*=\s*\{(.*?)\};", text, flags=re.S)
    out = {}
    if block:
        idx = 1
        for line in block.group(1).splitlines():
            m = re.search(r"//\s*(PAL_\w+)\s*(.*)", line)
            if m:
                out[m.group(1)] = (idx, m.group(2).strip())
                idx += 1
        out["PAL_CUSTOM"] = (
            0, "4 anchor colours set with ext-esp_led-seg-palette")
    return out


def main():
    text = SRC.read_text(encoding="utf-8")
    consts = parse_enums(text)
    consts.update(parse_palettes(text))

    lines = [
        ";@const-symbol-strings",
        "",
        "; GENERATED by gen_defs.py from esp_led_strip/code.c - DO NOT EDIT.",
        "; Run `make defs` after changing the C enums or the palette table.",
        "; code.c is the source of truth; these ids must match it exactly.",
        "",
        "@const-start",
    ]

    emitted = 0
    for prefix, header in GROUPS:
        members = sorted(((n, v, c) for n, (v, c) in consts.items()
                          if n.startswith(prefix)), key=lambda e: e[1])
        if not members:
            continue
        names = [n.replace("_", "-") for n, _, _ in members]
        width = max(len(n) for n in names)
        lines.append("")
        lines.append("; " + header)
        for (cname, value, comment), lname in zip(members, names):
            entry = f"(def {lname:<{width}} {value})"
            lines.append(f"{entry} ; {comment}" if comment else entry)
            emitted += 1

    lines += ["", "@const-end", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.name}: {emitted} constants")


if __name__ == "__main__":
    main()
