blank_issues_enabled: false
contact_links:
  - name: Discord development channel
    url: https://discord.com/channels/1346864089170710739/1347601377815429151
    about: "#refloat on Float with VESC"
