(def software-adc true)
(def software-adc2 true)
(def adc-touch 0.02)
(def temp-warning-motor 80)
(def temp-warning-fet 80)
(def bms-temp-hi 50)
(def bms-temp-lo 0)
(def show-batt-in-idle false)
(def idle-display 0)
(def last-alarm-code 0)
(def show-batt-idle-secret false)
(def min-speed 1)
(def button-safety-speed (/ 0.1 3.6))
(def alarm-tone true)
(def alarm-speed-threshold 0.5)
(def alarm-gyro-threshold 10)
(def alarm-voltage 24)
(def eco-speed (/ 7 3.6))
(def eco-current 0.6)
(def eco-watts 400)
(def eco-fw 0)
(def drive-speed (/ 17 3.6))
(def drive-current 0.7)
(def drive-watts 500)
(def drive-fw 0)
(def sport-speed (/ 22 3.6))
(def sport-current 1.0)
(def sport-watts 700)
(def sport-fw 0)
(def secret-enabled true)
(def secret-eco-speed (/ 27 3.6))
(def secret-eco-current 1.0)
(def secret-eco-watts 1000)
(def secret-eco-fw 0)
(def secret-drive-speed (/ 47 3.6))
(def secret-drive-current 1.0)
(def secret-drive-watts 1500)
(def secret-drive-fw 0)
(def secret-sport-speed (/ 1000 3.6))
(def secret-sport-current 1.0)
(def secret-sport-watts 2000)
(def secret-sport-fw 10)
(def apply-speed true)
(def apply-current true)
(def apply-watts true)
(def apply-fw true)
(def secret-presses 1)
(def secret-off-presses 3)
(def secret-off-combo 3)
(def secret-off-requires-lock false)
(def secret-combo 0)
(def secret-requires-lock false)
(def secret-exit-on-lock false)
(def lock-presses 2)
(def lock-combo 1)
(def mode-presses 2)
(def mode-combo 3)
(def mode-requires-lock false)
(def light-presses 1)
(def light-combo 3)
(def light-requires-lock false)
(def light-on-boot false)
(def light-offset-thr 0.0)
(def light-gain-thr 1.0)
(def light-offset-brk 0.0)
(def light-gain-brk 1.0)
(def boot-mode 1)
(def use-mph false)
(def bms-soc-enable false)
(def app-pin 0)
(def rear-light-enable false)
(def auto-taillight false)
(def brake-light-mode 1)
(def taillight-brightness 0.4)
(def tail-off-lock false)
(def head-off-lock false)
(def slip-erpm 1200.0)
(def slip-hold 2.0)
(def slip-time 0)
(def eco-om 1.0)
(def drive-om 1.0)
(def sport-om 1.0)
(def secret-eco-om 1.0)
(def secret-drive-om 1.0)
(def secret-sport-om 1.0)
(def apply-om false)
(def cruise-allow false)
(def cruise-enabled false)
(def cruise-delay 5.0)
(def cruise-deviation 1.0)
(def cruise-min-speed 5.0)
(def cruise-max-speed 35.0)
@const-start
(import "pkg@://vesc_packages/lib_code_server/code_server.vescpkg" 'code-server)
(read-eval-program code-server)
@const-end
(def model 2)
(def tx-base 7)
(def rx-hdr 0x5aa5)
(def rx-pre 4)
(def rx-o 1)
(def rx-sub 0)
(def tx-hdr-sum 0)
(def thr-idx 5)
(def brk-idx 6)
(def press-time (systime))
(def presses 0)
(def off false)
(def lock false)
(def speedmode 4)
(def light false)
(def unlock false)
(def use-defaults false)
(def alarm 0)
(def alarm-time (systime))
(def feedback 0)
(def beep-time (systime))
(def last-rx (systime))
(def rx-gap-avg 0.05)
(def lev-thr 0.0)
(def lev-brk 0.0)
(def lever-state 0)
(def lever-since (systime))
(def lever-armed true)
(def can-ids '())
(def can-ids-time 0)
(def gyro-src -1)
(def gyro-probe 0)
(def cur-speed-kmh 0.0)
(def cur-batt 0.0)
(def cur-vin 0.0)
(def cur-amps 0.0)
(def cur-bms-temp -100.0)
(def cur-range 0.0)
(def cur-trip 0)
(def cur-odo 0)
(def cur-runtime 0)
(def cur-fet 0.0)
(def cur-mot 0.0)
(def cur-fet-max 0.0)
(def cur-mot-max 0.0)
(def warn-temp false)
(def cur-maxkmh 0.0)
(def cur-cells 10)
(def cur-cap 0)
(def bms-active false)
(def bms-warn false)
(def app-boot-time (systime))
(def app-cache-time (systime))
(def app-slow-time (systime))
(def app-slow-step 0)
(def cur-wh-tot 0.0)
(def b0-wanted false)
(def app-dst 0x3e)
(def g2-aux 0x40)
(def app-todo 0)
(def levers-active false)
(def app-pend false)
(def power-pin 0)
(def dash-power-held false)
(def pend-dev 0)
(def app-pend2 false)
(def pend2-dev 0)
(def pend2-reg 0)
(def pend2-n 0)
(def pend-reg 0)
(def pend-n 0)
(def thr-rest 255)
(def brk-rest 255)
(def dash-tx-iv 0.05)
(def dash-tx-time (systime))
(def app-enable false)
(def cur-cell-mv 0)
(def cur-soh 100)
(def pwm-started false)
(def blink-state false)
(def blink-since (systime))
(def cruising false)
(def cruise-thr-released false)
(def cruise-blocked false)
(def cruise-ref 0.0)
(def cruise-since (systime))
(def cruise-shown-time (systime))
(def cruise-v1-start 0.3)
(def thr-corr-v 0.0)
(def dash-thr-raw 0)
(def dash-brk-raw 0)
(def calib-stage 'idle)
(def calib-phase 0)
(def calib-slot 0)
(def calib-slots 4)
(def calib-channel 'thr)
(def calib-since (systime))
(def calib-prep-duration 3.0)
(def calib-settle-duration 0.5)
(def calib-sample-duration 0.5)
(def calib-release-duration 3.0)
(def calib-off-sum 0.0) (def calib-off-cnt 0)
(def calib-on-sum 0.0) (def calib-on-cnt 0)
(def calib-off-rel 0.0) (def calib-on-rel 0.0)
@const-start
(def settings-version 420i32)
(def setting-defs '(
(ver-code 0 i 0)
(software-adc 1 b true)
(software-adc2 87 b true)
(tail-off-lock 95 b false)
(head-off-lock 96 b false)
(temp-warning-motor 4 f 80.0)
(temp-warning-fet 5 f 80.0)
(bms-temp-hi 97 f 50.0)
(bms-temp-lo 98 f 0.0)
(show-batt-in-idle 6 b false)
(min-speed-kmh 7 f 1.0)
(alarm-tone 8 b true)
(alarm-speed-threshold 9 f 0.5)
(alarm-gyro-threshold 10 f 10.0)
(alarm-voltage 11 f 24.0)
(eco-speed-kmh 12 f 7.0)
(eco-current 13 f 0.6)
(eco-watts 14 f 400.0)
(eco-fw 15 f 0.0)
(drive-speed-kmh 16 f 17.0)
(drive-current 17 f 0.7)
(drive-watts 18 f 500.0)
(drive-fw 19 f 0.0)
(sport-speed-kmh 20 f 22.0)
(sport-current 21 f 1.0)
(sport-watts 22 f 700.0)
(sport-fw 23 f 0.0)
(secret-enabled 24 b true)
(secret-eco-speed-kmh 25 f 27.0)
(secret-eco-current 26 f 1.0)
(secret-eco-watts 27 f 1000.0)
(secret-eco-fw 28 f 0.0)
(secret-drive-speed-kmh 29 f 47.0)
(secret-drive-current 30 f 1.0)
(secret-drive-watts 31 f 1500.0)
(secret-drive-fw 32 f 0.0)
(secret-sport-speed-kmh 33 f 1000.0)
(secret-sport-current 34 f 1.0)
(secret-sport-watts 35 f 2000.0)
(secret-sport-fw 36 f 10.0)
(model 37 i 2)
(apply-speed 38 b true)
(apply-current 39 b true)
(apply-watts 40 b true)
(apply-fw 41 b true)
(secret-presses 42 i 1)
(secret-off-presses 89 i 3)
(secret-off-combo 90 i 3)
(secret-off-requires-lock 91 b false)
(idle-display 92 i 0)
(secret-combo 43 i 0)
(secret-requires-lock 44 b false)
(lock-presses 45 i 2)
(lock-combo 46 i 1)
(mode-presses 51 i 2)
(mode-combo 52 i 3)
(light-presses 53 i 1)
(light-combo 54 i 3)
(light-on-boot 55 b false)
(button-speed-kmh 56 f 0.1)
(boot-mode 57 i 1)
(show-batt-idle-secret 58 b false)
(mode-requires-lock 59 b false)
(light-requires-lock 60 b false)
(use-mph 61 b false)
(rear-light-enable 62 b false)
(auto-taillight 63 b false)
(brake-light-mode 64 i 1)
(eco-om 65 f 1.0)
(drive-om 66 f 1.0)
(sport-om 67 f 1.0)
(secret-eco-om 68 f 1.0)
(secret-drive-om 69 f 1.0)
(secret-sport-om 70 f 1.0)
(apply-om 71 b false)
(bms-soc-enable 73 b false)
(cruise-enabled 74 b false)
(cruise-delay 75 f 5.0)
(cruise-deviation 76 f 1.0)
(cruise-min-speed 82 f 5.0)
(cruise-max-speed 83 f 35.0)
(secret-exit-on-lock 77 b false)
(light-offset-thr 78 f 0.0)
(light-offset-brk 79 f 0.0)
(light-gain-thr 80 f 1.0)
(light-gain-brk 81 f 1.0)
(app-pin 84 i 0)
(taillight-brightness 94 f 0.4)
(app-enable 85 b false)
(power-pin 88 i 0)
(cruise-allow 93 b false)
))
(def setting-groups '(
(misc light-on-boot button-speed-kmh use-mph bms-soc-enable secret-exit-on-lock
light-offset-thr light-gain-thr light-offset-brk light-gain-brk app-pin power-pin
head-off-lock)
(general software-adc software-adc2 show-batt-in-idle show-batt-idle-secret
min-speed-kmh app-enable idle-display)
(temps temp-warning-motor temp-warning-fet bms-temp-hi bms-temp-lo)
(modes eco-speed-kmh eco-current eco-watts eco-fw
drive-speed-kmh drive-current drive-watts drive-fw
sport-speed-kmh sport-current sport-watts sport-fw
boot-mode eco-om drive-om sport-om)
(secret secret-enabled
secret-eco-speed-kmh secret-eco-current secret-eco-watts secret-eco-fw
secret-drive-speed-kmh secret-drive-current secret-drive-watts secret-drive-fw
secret-sport-speed-kmh secret-sport-current secret-sport-watts secret-sport-fw
secret-eco-om secret-drive-om secret-sport-om)
(apply apply-speed apply-current apply-watts apply-fw apply-om)
(gesture secret-presses secret-combo secret-requires-lock
lock-presses lock-combo
mode-presses mode-combo mode-requires-lock
light-presses light-combo light-requires-lock
secret-off-presses secret-off-combo secret-off-requires-lock)
(rear rear-light-enable auto-taillight brake-light-mode taillight-brightness
tail-off-lock)
(cruise cruise-allow cruise-delay cruise-deviation cruise-min-speed cruise-max-speed)
(alarm alarm-tone alarm-speed-threshold alarm-gyro-threshold alarm-voltage)
))
(def speed-settings '(min-speed-kmh button-speed-kmh eco-speed-kmh drive-speed-kmh
sport-speed-kmh secret-eco-speed-kmh secret-drive-speed-kmh secret-sport-speed-kmh))
(def last-button-state false)
(defun read-setting (name)
{
(var d (assoc setting-defs name))
(var ty (second d))
(var v (if (eq ty 'f) (eeprom-read-f (first d)) (eeprom-read-i (first d))))
(if (eq v nil) 'unset (if (eq ty 'b) (!= v 0) v))
}
)
(defun write-setting (name val)
{
(var d (assoc setting-defs name))
(var addr (first d))
(var ty (second d))
(var new (if (eq ty 'b) (if val 1 0) val))
(var dflt (let ((x (ix d 2))) (if (eq ty 'b) (if x 1 0) x)))
(var cur (if (eq ty 'f) (eeprom-read-f addr) (eeprom-read-i addr)))
(if (if (eq cur nil) (!= new dflt) (!= cur new))
{
(if (eq ty 'f) (eeprom-store-f addr new) (eeprom-store-i addr new))
(sleep 0.05)
}
)
}
)
(defun valid-model (m)
(and (not (eq m 'unset)) (not (eq m nil)) (>= m 0) (<= m 3))
)
(defun restore-defaults ()
{
(write-setting 'ver-code settings-version)
(write-setting 'model 2)
(loopforeach s setting-defs
(let ((n (ix s 0)))
(if (not (or (eq n 'model) (eq n 'ver-code)))
(write-setting n (ix s 3)))))
}
)
(defun load-settings ()
{
(if (not-eq (read-setting 'ver-code) settings-version)
{
(write-setting 'ver-code settings-version)
(write-setting 'model 2)
}
)
(loopforeach g setting-groups
(loopforeach n (cdr g)
(if (not (member n speed-settings))
(set n (let ((v (read-setting n))) (if (eq v 'unset) (eval n) v))))))
(set 'cruise-enabled (let ((v (read-setting 'cruise-enabled))) (if (eq v 'unset) cruise-enabled v)))
(set 'min-speed (setting-def 'min-speed-kmh))
(set 'eco-speed (/ (setting-def 'eco-speed-kmh) 3.6))
(set 'drive-speed (/ (setting-def 'drive-speed-kmh) 3.6))
(set 'sport-speed (/ (setting-def 'sport-speed-kmh) 3.6))
(set 'secret-eco-speed (/ (setting-def 'secret-eco-speed-kmh) 3.6))
(set 'secret-drive-speed (/ (setting-def 'secret-drive-speed-kmh) 3.6))
(set 'secret-sport-speed (/ (setting-def 'secret-sport-speed-kmh) 3.6))
(set 'button-safety-speed (/ (setting-def 'button-speed-kmh) 3.6))
(if (< light-gain-thr 0.05) (set 'light-gain-thr 1.0))
(if (< light-gain-brk 0.05) (set 'light-gain-brk 1.0))
(var m (read-setting 'model))
(if (not (valid-model m)) {
(setq m 2)
(write-setting 'model m)
})
(set 'model m)
}
)
(defun apply-software-adc ()
(let ((d1 (or software-adc (= power-pin 1)))
(d2 (or software-adc2 (= power-pin 2))))
{
(let ((d (cond ((and d1 d2) 1) (d1 2) (d2 3) (t 0))))
(if (= d 0)
(app-adc-detach 2 1)
(app-adc-detach 3 d)
)
)
(if (and d1 (not software-adc)) (app-adc-override 0 0))
(if (and d2 (not software-adc2)) (app-adc-override 1 0))
(if (and (not software-adc) (not software-adc2) (not (eq calib-stage 'idle))) {
(set 'calib-stage 'idle)
(send-data "calib-aborted")
})
}
)
)
(defun apply-dash-power ()
(let ((pin (if (= power-pin 1) 'pin-adc1 'pin-adc2)))
(if (> power-pin 0)
(if (not (eq dash-power-held pin)) {
(if dash-power-held (gpio-configure dash-power-held 'pin-mode-analog))
(gpio-write pin (if off 0 1))
(gpio-configure pin 'pin-mode-out)
(set 'dash-power-held pin)
})
(if dash-power-held {
(gpio-configure dash-power-held 'pin-mode-analog)
(set 'dash-power-held false)
})
)
)
)
(defun apply-runtime-settings ()
{
(load-settings)
(trap (let ((v (* 0.4 (conf-get 'adc-tc-max-diff)))) (if (> v 60) (setq slip-erpm v))))
(if (!= model 2) {
(apply-software-adc)
(apply-dash-power)
(apply-mode)
(if rear-light-enable
(if (not pwm-started) {
(pwm-start 200 0)
(set 'pwm-started true)
})
(if pwm-started (pwm-set-duty 0.0))
)
})
}
)
(defun save-group (g vals)
{
(var i 0)
(loopforeach n (assoc setting-groups g)
{
(write-setting n (ix vals i))
(setq i (+ i 1))
}
)
(send-data "ack")
}
)
(defun save-model (m)
{
(write-setting 'model (if (valid-model m) m 2))
(send-data "model-ok")
}
)
(defun finish-settings-save ()
{
(apply-runtime-settings)
(send-settings)
(send-data "ok")
}
)
(defun restore-settings-ui ()
{
(restore-defaults)
(apply-runtime-settings)
(send-data "reset-ok")
}
)
(defun ctrl-lock (on)
(if (and (not (eq on lock)) (<= (abs (get-speed)) 1.0))
(toggle-lock)
)
)
(defun ctrl-light (on)
(set 'light on)
)
(defun ctrl-mode (m)
(if (or (= m 1) (= m 2) (= m 4)) {
(set 'speedmode m)
(apply-mode)
})
)
(defun ctrl-secret (on)
(if (and secret-enabled (not (eq on unlock)))
(toggle-secret)
)
)
(defun ctrl-cruise (on)
{
(set 'cruise-enabled (and on cruise-allow))
(write-setting 'cruise-enabled cruise-enabled)
(if (not cruise-enabled) (cruise-cancel))
}
)
(defun boot-state ()
{
(set 'speedmode (if (or (= boot-mode 1) (= boot-mode 2) (= boot-mode 4)) boot-mode 4))
(set 'light light-on-boot)
}
)
(defun ctrl-power (on)
(if on
(if off {
(set 'off false)
(set 'feedback 1)
(set 'unlock false)
(boot-state)
(apply-mode)
(stats-reset)
})
(if (and (not off) (not lock) (<= (abs (get-speed)) 1.0)) {
(set 'light false)
(set 'feedback 1)
(set 'unlock false)
(apply-mode)
(set 'off true)
})
)
)
(defun tf (v) (if v "true " "false "))
(defun send-state ()
(let ((whkm (send-state-whkm)))
(send-data (str-merge
"state "
(tf off)
(tf lock)
(tf light)
(tf unlock)
(str-from-n speedmode "%d ")
(str-from-n cur-batt "%.0f ")
(str-from-n cur-vin "%.1f ")
(str-from-n (abs cur-speed-kmh) "%.1f ")
(str-from-n (* cur-vin cur-amps) "%.0f ")
(str-from-n whkm "%.1f ")
(str-from-n cur-range "%.1f ")
(str-from-n cur-amps "%.1f ")
(str-from-n (send-state-maxkmh) "%.0f ")
(tf cruising)
(tf cruise-enabled)
(tf cruise-allow)
(tf img-ok)
(str-from-n cur-fet-max "%.0f ")
(str-from-n cur-mot-max "%.0f ")
(tf secret-enabled)
(str-from-n (+ 1 (length (can-devs))) "%d ")
(str-from-n (get-fault) "%d ")
(str-from-n (wheel-slip) "%d ")
(str-from-n cur-bms-temp "%.0f ")
(str-from-n (secs-since app-boot-time) "%.0f")
))
)
)
(defun send-state-maxkmh ()
(* 3.6 (if unlock
(cond ((= speedmode 1) secret-drive-speed) ((= speedmode 2) secret-eco-speed) (t secret-sport-speed))
(cond ((= speedmode 1) drive-speed) ((= speedmode 2) eco-speed) (t sport-speed))
))
)
(defun send-state-whkm () {
(var dist-km (/ (get-dist-abs) 1000.0))
(if (> dist-km 0.05)
(/ (- (setup-wh) (setup-wh-chg)) dist-km)
0.0
)
})
(defun send-state-range () {
(var whkm (send-state-whkm))
(if (> whkm 0.1)
(/ (* (get-batt) cur-wh-tot) whkm)
0.0
)
})
(defun setting-def (n)
(let ((v (if use-defaults 'unset (read-setting n))))
(if (eq v 'unset) (ix (assoc setting-defs n) 2) v))
)
(defun setting-str (n)
(let ((d (assoc setting-defs n)) (v (setting-def n)))
{
(cond
((eq (second d) 'b) (if v "true" "false"))
((eq (second d) 'f) (str-from-n v "%.3f"))
(t (str-from-n v "%d"))
)
}
)
)
(defun send-groups ()
(loopforeach g setting-groups
{
(var line (to-str (first g)))
(loopforeach n (cdr g)
(setq line (str-merge line " " (setting-str n))))
(send-data line)
(sleep 0.05)
}
)
)
(defun send-settings ()
{
(send-data (str-merge "model " (setting-str 'model)))
(sleep 0.05)
(send-groups)
}
)
(defun send-defaults ()
{
(set 'use-defaults true)
(send-groups)
(set 'use-defaults false)
}
)
(defun event-handler ()
(loopwhile t
(recv
((event-data-rx . (? data)) (trap (eval (read data))))
(_ nil)
)))
@const-end
@const-start
(defun calib-reset-accum()
{
(set 'calib-off-sum 0.0) (set 'calib-off-cnt 0)
(set 'calib-on-sum 0.0) (set 'calib-on-cnt 0)
}
)
(defun calib-slot-light(slot) (= (mod slot 2) 1))
(defun calib-add(val)
(if (calib-slot-light calib-slot)
{ (set 'calib-on-sum (+ calib-on-sum val)) (set 'calib-on-cnt (+ calib-on-cnt 1)) }
{ (set 'calib-off-sum (+ calib-off-sum val)) (set 'calib-off-cnt (+ calib-off-cnt 1)) }
)
)
(defun calib-off-avg() (if (> calib-off-cnt 0) (/ calib-off-sum calib-off-cnt) 0.0))
(defun calib-on-avg() (if (> calib-on-cnt 0) (/ calib-on-sum calib-on-cnt) 0.0))
(defun calib-finish-regression(label off-rel off-full on-rel on-full)
{
(var off-range (- off-full off-rel))
(if (< off-range 0.3)
(send-data (str-merge "calib-error " label))
{
(var gain (/ (- on-full on-rel) off-range))
(var offset (- on-rel (* gain off-rel)))
(if (< gain 0.3) (setq gain 0.3))
(if (> gain 3.0) (setq gain 3.0))
(if (< offset -1.5) (setq offset -1.5))
(if (> offset 1.5) (setq offset 1.5))
(send-data (str-merge "calib-result " label " "
(str-from-n offset "%.3f ") (str-from-n gain "%.3f ")
(str-from-n off-rel "%.3f ") (str-from-n off-full "%.3f ")
(str-from-n on-rel "%.3f ") (str-from-n on-full "%.3f")))
}
)
}
)
(defun calib-phase-label(phase) (if (= phase 0) "rel" "full"))
(defun calib-slot-index() (+ (* calib-phase calib-slots) calib-slot 1))
(defun calib-slot-total() (* calib-slots 2))
(defun calib-slot-progress()
(str-merge (str-from-n (calib-slot-index) "%d") " " (str-from-n (calib-slot-total) "%d"))
)
(defun calib-can-start() (and (not off) (<= (abs (get-speed)) 1.0)))
(defun calib-begin-prep(phase)
{
(set 'calib-phase phase)
(set 'calib-slot 0)
(set 'light false)
(calib-reset-accum)
(set 'calib-stage 'prep)
(set 'calib-since (systime))
(send-data (str-merge "calib-stage prep " (calib-phase-label phase)))
}
)
(defun calib-begin-settle()
{
(set 'light (calib-slot-light calib-slot))
(set 'calib-stage 'settle)
(set 'calib-since (systime))
(send-data (str-merge "calib-stage settle " (calib-phase-label calib-phase) " " (calib-slot-progress)))
}
)
(defun calib-begin-sample()
{
(set 'calib-stage 'measure)
(set 'calib-since (systime))
(send-data (str-merge "calib-stage measure " (calib-phase-label calib-phase) " " (calib-slot-progress)))
}
)
(defun calib-finish-slot()
{
(set 'calib-slot (+ calib-slot 1))
(if (< calib-slot calib-slots)
(calib-begin-settle)
{
(var off-avg (calib-off-avg))
(var on-avg (calib-on-avg))
(var ch calib-channel)
(send-data (str-merge "calib-progress " (if (eq ch 'thr) "thr " "brk ")
(calib-phase-label calib-phase) " "
(str-from-n off-avg "%.3f ") (str-from-n on-avg "%.3f")))
(if (= calib-phase 0)
{
(set 'calib-off-rel off-avg)
(set 'calib-on-rel on-avg)
(calib-begin-prep 1)
}
{
(set 'light false)
(calib-finish-regression (if (eq ch 'thr) "thr" "brk")
calib-off-rel off-avg calib-on-rel on-avg)
(set 'calib-stage 'release)
(set 'calib-since (systime))
(send-data (str-merge "calib-stage release " (if (eq ch 'thr) "thr" "brk")))
}
)
}
)
}
)
(defun calib-start-channel(channel)
(if (calib-can-start)
{
(set 'calib-channel channel)
(calib-begin-prep 0)
}
(send-data "calib-refused")
)
)
(defun calib-start-thr() (calib-start-channel 'thr))
(defun calib-start-brk() (calib-start-channel 'brk))
(defunret adc-input (off)
{
(if (not (or software-adc software-adc2)) (return nil))
(let ((gap (secs-since last-rx)))
(if (< gap 1.0)
(if (> gap rx-gap-avg)
(set 'rx-gap-avg gap)
(set 'rx-gap-avg (+ (* 0.98 rx-gap-avg) (* 0.02 gap)))
)
)
)
(set 'last-rx (systime))
(set 'dash-thr-raw (bufget-u8 uart-buf (+ thr-idx off)))
(set 'dash-brk-raw (bufget-u8 uart-buf (+ brk-idx off)))
(var thr-raw-v (/ dash-thr-raw 77.2))
(var brk-raw-v (/ dash-brk-raw 77.2))
(var throttle (if light (/ (- thr-raw-v light-offset-thr) light-gain-thr) thr-raw-v))
(var brake (if light (/ (- brk-raw-v light-offset-brk) light-gain-brk) brk-raw-v))
(if (and (> dash-thr-raw 16) (< dash-thr-raw thr-rest)) (set 'thr-rest dash-thr-raw))
(if (and (> dash-brk-raw 16) (< dash-brk-raw brk-rest)) (set 'brk-rest dash-brk-raw))
(set 'levers-active (or (> dash-thr-raw (+ thr-rest 10))
(> dash-brk-raw (+ brk-rest 10))))
(if (< throttle 0.0) (setq throttle 0.0))
(if (> throttle 3.3) (setq throttle 3.3))
(if (< brake 0.0) (setq brake 0.0))
(if (> brake 3.3) (setq brake 3.3))
(set 'thr-corr-v throttle)
(if (and cruising (not cruise-thr-released)) (setq throttle 0.0))
(if (eq calib-stage 'idle)
{
(if software-adc (app-adc-override 0 throttle))
(if software-adc2 (app-adc-override 1 brake))
}
{
(if software-adc (app-adc-override 0 0))
(if software-adc2 (app-adc-override 1 0))
}
)
(if (and (not (eq calib-stage 'idle)) (not (eq calib-stage 'release)) (not (calib-can-start)))
{
(set 'calib-stage 'idle)
(send-data "calib-aborted")
}
(cond
((eq calib-stage 'prep)
(if (> (secs-since calib-since) calib-prep-duration) (calib-begin-settle))
)
((eq calib-stage 'settle)
(if (> (secs-since calib-since) calib-settle-duration) (calib-begin-sample))
)
((eq calib-stage 'measure)
(if (> (secs-since calib-since) calib-sample-duration)
(calib-finish-slot)
(calib-add (if (eq calib-channel 'thr) thr-raw-v brk-raw-v))
)
)
((eq calib-stage 'release)
(if (> (secs-since calib-since) calib-release-duration)
{
(set 'calib-stage 'idle)
(send-data (str-merge "calib-stage idle " (if (eq calib-channel 'thr) "thr" "brk")))
}
)
)
)
)
}
)
(defun handle-taillight()
(if rear-light-enable {
(var live (and (not off) (not (and lock tail-off-lock))))
(var base (and live (or light auto-taillight)))
(var braking (and live (> lev-brk adc-touch)))
(pwm-set-duty
(if braking
(cond
((= brake-light-mode 1) 1.0)
((= brake-light-mode 2) {
(if (> (secs-since blink-since) 0.15) {
(set 'blink-state (not blink-state))
(set 'blink-since (systime))
})
(if blink-state 1.0 0.0)
})
(t (if base taillight-brightness 0.0))
)
(if base taillight-brightness 0.0)
)
)
})
)
(defun cruise-cancel()
(if cruising {
(set 'cruising false)
(set 'cruise-blocked true)
(app-adc-override 3 0)
(set 'feedback 1)
})
)
(defun handle-cruise(speed-kmh)
(if (and cruise-allow cruise-enabled (not off) (not lock))
{
(var thr lev-thr)
(var brk lev-brk)
(if cruising
{
(if (if software-adc
(< thr-corr-v cruise-v1-start)
(<= thr adc-touch))
(set 'cruise-thr-released true)
)
(if (or (and cruise-thr-released (> thr adc-touch))
(> brk adc-touch))
(cruise-cancel)
)
}
(if (<= thr adc-touch)
{
(set 'cruise-blocked false)
(set 'cruise-ref speed-kmh)
(set 'cruise-since (systime))
}
(if (and (not cruise-blocked) (>= speed-kmh min-speed)
(>= speed-kmh cruise-min-speed) (<= speed-kmh cruise-max-speed))
{
(if (> (abs (- speed-kmh cruise-ref)) cruise-deviation) {
(set 'cruise-ref speed-kmh)
(set 'cruise-since (systime))
})
(if (> (secs-since cruise-since) cruise-delay) {
(set 'cruising true)
(set 'cruise-thr-released false)
(set 'cruise-v1-start (conf-get 'adc-v1-start))
(set 'cruise-shown-time (systime))
(app-adc-override 3 1)
(set 'feedback 2)
(set 'cruise-since (systime))
})
}
{
(set 'cruise-ref speed-kmh)
(set 'cruise-since (systime))
}
)
)
)
}
(cruise-cancel)
)
)
(defun handle-features()
{
(set 'cur-speed-kmh (* (get-lowest-speed) 3.6))
(check-slip)
(trap
(if (and bms-soc-enable (> (get-bms-val 'bms-soc) 0))
{
(set 'bms-active true)
(set 'cur-batt (* (get-bms-val 'bms-soc) 100))
(var bt (get-bms-val 'bms-temp-cell-max))
(set 'cur-bms-temp bt)
(set 'bms-warn (or (> bt bms-temp-hi) (< bt bms-temp-lo)))
}
{
(set 'cur-batt (* (get-batt) 100))
(set 'bms-active false)
(set 'bms-warn false)
(set 'cur-bms-temp -100.0)
}
)
)
(var current-speed cur-speed-kmh)
(var wd (* 8 rx-gap-avg))
(if (< wd 0.5) (setq wd 0.5))
(if (> wd 1.5) (setq wd 1.5))
(if (and (or software-adc software-adc2) (> (secs-since last-rx) wd))
(cruise-cancel)
)
(trap (handle-cruise current-speed))
(if (or off lock (< current-speed min-speed))
(if (not (app-is-output-disabled))
{
(app-adc-override 0 0)
(app-adc-override 1 0)
(app-disable-output -1)
(stop-current)
}
)
(if (app-is-output-disabled)
(app-disable-output 0)
)
)
(trap (app-run-todo))
(trap (app-cache-update))
(trap (handle-taillight))
(if dash-power-held
(gpio-write dash-power-held
(if (and off (or (and (= feedback 0) (> (secs-since beep-time) 0.15))
(> (secs-since last-rx) 0.5)))
0 1)))
(if (and (not software-adc) (not software-adc2)) {
(if (= power-pin 1) (app-adc-override 0 0))
(if (= power-pin 2) (app-adc-override 1 0))
})
(handle-lock (abs current-speed))
}
)
(defun highest-temp (local canget)
(let ((hi local))
{
(trap (loopforeach i (can-devs)
(let ((c (canget i))) (if (> c hi) (setq hi c)))))
hi
}
)
)
(defun idle-value ()
(cond
((= idle-display 1) (rnd cur-vin))
((= idle-display 2) (rnd cur-fet-max))
((= idle-display 3) (rnd cur-mot-max))
(t (rnd cur-batt))
)
)
(defun build-dash-frame ()
{
(var current-speed (abs cur-speed-kmh))
(var disp-speed (rnd (if use-mph (* current-speed 0.621371) current-speed)))
(var battery (rnd cur-batt))
(var mode-base (+ (if (= speedmode 1) 0 speedmode) (if use-mph 64 0)))
(if (= model 3)
(bufset-u8 tx-frame tx-base (+ mode-base
(if off 16 0)
(if lock 32 0)
(if (or warn-temp bms-warn) 128 0)))
(if off
(bufset-u8 tx-frame tx-base 16)
(if lock
(bufset-u8 tx-frame tx-base 32)
(if (or warn-temp bms-warn)
(bufset-u8 tx-frame tx-base (+ 128 mode-base))
(bufset-u8 tx-frame tx-base mode-base)
)
)
)
)
(if lock
(bufset-u8 tx-frame (+ tx-base 1) 0)
(bufset-u8 tx-frame (+ tx-base 1) battery)
)
(var lamp (if (= model 1) 100 1))
(if (not off)
(if (> alarm 4)
(bufset-u8 tx-frame (+ tx-base 2) lamp)
(bufset-u8 tx-frame (+ tx-base 2) (+ (if (and light (or (not-eq calib-stage 'idle) (not (and lock head-off-lock)))) lamp 0)
(if (and (= model 3) cruising) 4 0)))
)
(bufset-u8 tx-frame (+ tx-base 2) 0)
)
(if lock
(bufset-u8 tx-frame (+ tx-base 4) 0)
(if (and cruising (< (secs-since cruise-shown-time) 3))
(bufset-u8 tx-frame (+ tx-base 4) 125)
(if (if unlock show-batt-idle-secret show-batt-in-idle)
(if (> current-speed 1)
(bufset-u8 tx-frame (+ tx-base 4) disp-speed)
(bufset-u8 tx-frame (+ tx-base 4) (idle-value)))
(bufset-u8 tx-frame (+ tx-base 4) disp-speed)
)
)
)
(if (> alarm 0)
(bufset-u8 tx-frame (+ tx-base 5) 99)
(bufset-u8 tx-frame (+ tx-base 5) (get-fault))
)
}
)
(defun seal-dash-frame ()
{
(trap (build-dash-frame))
(if (> feedback 0)
{
(bufset-u8 tx-frame (+ tx-base 3) 1)
(set 'feedback (- feedback 1))
(set 'beep-time (systime))
}
(bufset-u8 tx-frame (+ tx-base 3) 0)
)
(var crc-end (- (buflen tx-frame) 2))
(var crcout tx-hdr-sum)
(looprange i tx-base crc-end
(setq crcout (+ crcout (bufget-u8 tx-frame i))))
(setq crcout (bitwise-xor crcout 0xFFFF))
(bufset-u8 tx-frame crc-end crcout)
(bufset-u8 tx-frame (+ crc-end 1) (shr crcout 8))
}
)
(defun update-dash () { (seal-dash-frame) (uart-write tx-frame) })
(def app-ver 0x0700)
(defun app-build-serial ()
(let ((n 0))
{
(trap (loopforeach b (sysinfo 'uuid) (setq n (+ (* n 31) b))))
(var lo (mod (bitwise-and n 0x7FFFFFFF) 100000))
(var hi (mod (bitwise-and (shr n 7) 0x7FFFFFFF) 100000))
(var s (str-merge "VESC" (str-from-n hi "%05d") (str-from-n lo "%05d")))
(looprange i 0 14 (bufset-u8 app-serial i (bufget-u8 s i)))
(looprange i 0 5 (bufset-u8 app-cpuid i
(+ (shl (- (bufget-u8 s (+ 4 (* i 2))) 48) 4)
(- (bufget-u8 s (+ 5 (* i 2))) 48))))
}
)
)
(defun app-build-pin ()
(let ((s (str-from-n app-pin "%06d")))
(looprange i 0 6 (bufset-u8 app-pin-buf i (bufget-u8 s i)))
)
)
(defun app-word (buf idx)
(+ (bufget-u8 buf (* idx 2)) (shl (bufget-u8 buf (+ (* idx 2) 1)) 8))
)
(defun rnd (v) (to-i (if (< v 0) (- v 0.5) (+ v 0.5))))
(defun app-clamp16 (v)
(cond ((> v 32767) 32767) ((< v -32768) -32768) (t (rnd v)))
)
(defun app-sysinfo (key) (let ((v 0)) { (trap (setq v (sysinfo key))) (to-i v) }))
(defun app-cache-update ()
{
(if (> (secs-since app-cache-time) 0.2) {
(set 'app-cache-time (systime))
(set 'cur-vin (get-vin))
(set 'cur-amps (setup-current-in))
(set 'cur-fet (get-temp-fet))
(set 'cur-mot (get-temp-mot))
(set 'cur-fet-max (highest-temp cur-fet canget-temp-fet))
(set 'cur-mot-max (highest-temp cur-mot canget-temp-motor))
(set 'warn-temp (or (> cur-fet-max temp-warning-fet)
(> cur-mot-max temp-warning-motor)))
(set 'cur-cell-mv (app-clamp16 (/ (* cur-vin 1000) cur-cells)))
(if bms-active
(trap {
(set 'cur-soh (app-clamp16 (* (get-bms-val 'bms-soh) 100)))
(looprange i 0 (if (> cur-cells 15) 15 cur-cells) {
(var mv (app-clamp16 (* (get-bms-val 'bms-v-cell i) 1000)))
(bufset-u8 app-cells (* i 2) (bitwise-and mv 0xFF))
(bufset-u8 app-cells (+ (* i 2) 1) (bitwise-and (shr mv 8) 0xFF))
})
})
)
(if (!= model 1)
{
(build-app-frame app-f-b4 0xb4 6)
(build-app-frame app-f-7b 0x7b 6)
(build-app-frame app-f-75 0x75 2)
(build-app-frame-from app-f-33 0 0x22 0x33 4 true)
(build-app-frame-from app-f-35 0 0x22 0x35 2 true)
}
)
})
(if (> (secs-since app-slow-time) 0.5) {
(set 'app-slow-time (systime))
(cond
((= app-slow-step 0) {
(set 'cur-wh-tot (* 0.85 (conf-get 'si-battery-ah) (* 3.7 (conf-get 'si-battery-cells))))
(set 'cur-range (send-state-range))
(set 'cur-trip (to-i (get-dist-abs)))
})
((= app-slow-step 1) {
(set 'cur-odo (app-sysinfo 'odometer))
(set 'cur-runtime (app-sysinfo 'runtime))
(set 'cur-maxkmh (send-state-maxkmh))
})
((= app-slow-step 2)
(if (!= model 1) {
(build-app-frame-from app-f-31 0 0x22 0x31 2 true)
(build-app-frame-from app-f-40 0 0x22 0x40 30 true)
(build-app-frame app-f-25 0x25 2)
})
)
(t (if (and b0-wanted (!= model 1)) {
(set 'b0-wanted false)
(build-app-frame app-f-b0 0xb0 52)
}))
)
(set 'app-slow-step (mod (+ app-slow-step 1) 4))
})
}
)
(defun app-speed-01 () (app-clamp16 (* (abs cur-speed-kmh) 10)))
(defun app-trip-m () cur-trip)
(defun app-volt-cv () (app-clamp16 (* cur-vin 100)))
(defun app-amp-ca () (app-clamp16 (* cur-amps 100)))
(defun app-range-10m () (app-clamp16 (* cur-range 100)))
(defun app-fet-01 () (app-clamp16 (* cur-fet 10)))
(defun app-cell-mv (i) (if bms-active (app-word app-cells i) cur-cell-mv))
(defunret app-pend-buf ()
{
(if (= pend-dev 0x22)
(return (cond
((and (= pend-reg 0x33) (= pend-n 4)) app-f-33)
((and (= pend-reg 0x35) (= pend-n 2)) app-f-35)
((and (= pend-reg 0x31) (= pend-n 2)) app-f-31)
((and (= pend-reg 0x40) (= pend-n 30)) app-f-40)
(t nil)
))
)
(cond
((and (= pend-reg 0xb4) (= pend-n 6)) app-f-b4)
((and (= pend-reg 0xb0) (= pend-n 52)) app-f-b0)
((and (= pend-reg 0x7b) (= pend-n 6)) app-f-7b)
((and (= pend-reg 0x1a) (= pend-n 2)) app-f-1a)
((and (= pend-reg 0x25) (= pend-n 2)) app-f-25)
((and (= pend-reg 0x3b) (= pend-n 2)) app-f-3b)
((and (= pend-reg 0x75) (= pend-n 2)) app-f-75)
((and (= pend-reg 0xda) (= pend-n 12)) app-f-da)
(t nil)
)
}
)
(defun combo-buf (al)
(cond ((= al 11) combo11) ((= al 13) combo13) ((= al 15) combo15)
((= al 21) combo21) ((= al 39) combo39) ((= al 61) combo61) (t nil))
)
(defun send-dash-and-app ()
(let ((ab (if (or (= model 1) app-pend2) nil (app-pend-buf))))
{
(set 'app-pend false)
(seal-dash-frame)
(if app-pend2
{
(set 'app-pend2 false)
(var dl (buflen tx-frame))
(var l1 (app-fr-len pend-n))
(var cb (array-create (+ dl l1 (app-fr-len pend2-n))))
(trap {
(bufcpy cb 0 tx-frame 0 dl)
(build-app-frame-from cb dl pend-dev pend-reg pend-n (= pend-dev 0x22))
(build-app-frame-from cb (+ dl l1) pend2-dev pend2-reg pend2-n
(= pend2-dev 0x22))
(uart-write cb)
})
(free cb)
}
(if (eq ab nil)
{
(var dl (buflen tx-frame))
(var cb (array-create (+ dl (app-fr-len pend-n))))
(trap {
(bufcpy cb 0 tx-frame 0 dl)
(build-app-frame-from cb dl pend-dev pend-reg pend-n (= pend-dev 0x22))
(uart-write cb)
})
(free cb)
}
(let ((cb (combo-buf (buflen ab))) (dl (buflen tx-frame)))
(if (eq cb nil)
{ (uart-write tx-frame) (uart-write ab) }
{
(bufcpy cb 0 tx-frame 0 dl)
(bufcpy cb dl ab 0 (buflen ab))
(uart-write cb)
}
)
)
))
}
)
)
(defun build-app-frame-from (buf at dev reg n bms)
{
(var xm (= model 1))
(var p (+ at (if xm 6 7)))
(var crc (+ n reg))
(if xm
(let ((a (if bms 0x25 0x23)))
{
(bufset-u16 buf at 0x55aa)
(bufset-u8 buf (+ at 2) (+ n 2))
(bufset-u8 buf (+ at 3) a)
(bufset-u8 buf (+ at 4) 0x01)
(setq crc (+ crc 2 a 0x01))
}
)
{
(bufset-u16 buf at 0x5aa5)
(bufset-u8 buf (+ at 2) n)
(bufset-u8 buf (+ at 3) dev)
(bufset-u8 buf (+ at 4) app-dst)
(bufset-u8 buf (+ at 5) 0x04)
(setq crc (+ crc dev app-dst 0x04))
}
)
(bufset-u8 buf (- p 1) reg)
(looprange i 0 (/ n 2) {
(var w (if bms (xm-bms-word (+ reg i))
(if xm (xm-word (+ reg i)) (nb-word (+ reg i)))))
(var lo (bitwise-and w 0xFF))
(var hi (bitwise-and (shr w 8) 0xFF))
(bufset-u8 buf (+ p (* i 2)) lo)
(bufset-u8 buf (+ p (* i 2) 1) hi)
(setq crc (+ crc lo hi))
})
(setq crc (bitwise-xor crc 0xFFFF))
(bufset-u8 buf (+ p n) (bitwise-and crc 0xFF))
(bufset-u8 buf (+ p n 1) (bitwise-and (shr crc 8) 0xFF))
}
)
(defun build-app-frame (buf reg n) (build-app-frame-from buf 0 0x20 reg n false))
(defun app-cap-mah () cur-cap)
(defun app-bool-word ()
(+ (if (= speedmode 2) 1 0) (if lock 2 0) (if (> alarm 0) 4 0) 2048)
)
(defun app-workmode () (cond ((= speedmode 2) 1) ((= speedmode 4) 2) (t 0)))
(defun app-refresh-7b () (if (!= model 1) (build-app-frame app-f-7b 0x7b 6)))
(defun app-todo+ (bit) (set 'app-todo (bitwise-or app-todo bit)))
(defun app-write (reg val)
(cond
((= reg 0x70) (if (and (!= val 0) (not lock) (<= (abs cur-speed-kmh) 0.5))
(app-todo+ 32)))
((= reg 0x71) (if (and (!= val 0) lock (<= (abs cur-speed-kmh) 0.5))
(app-todo+ 32)))
((= reg 0x75) (let ((m (cond ((= val 1) 2) ((= val 2) 4) (t 1))))
(if (!= m speedmode) {
(set 'speedmode m)
(app-todo+ 16)
})))
((= reg 0x7a) (let ((v (!= val 0)))
(if (not (eq v light)) {
(set 'light v)
(app-refresh-7b)
})))
((= reg 0x7c) (let ((v (and (!= val 0) cruise-allow)))
(if (not (eq v cruise-enabled)) {
(set 'cruise-enabled v)
(app-refresh-7b)
(app-todo+ 1)
})))
((= reg 0x7d) (let ((v (!= val 0)))
(if (not (eq v auto-taillight)) {
(set 'auto-taillight v)
(app-refresh-7b)
(app-todo+ 2)
})))
((= reg 0x7b) (let ((m (cond ((= val 1) 1) ((= val 2) 4) (t 2))))
(if (!= m speedmode) {
(set 'speedmode m)
(app-todo+ 16)
})))
((= reg 0x77) (let ((u (!= val 0)))
(if (not (eq u unlock)) {
(set 'unlock u)
(app-todo+ 16)
})))
((= reg 0x76) (let ((v (!= val 0)))
(if (not (eq v light)) {
(set 'light v)
(app-refresh-7b)
})))
((= reg 0x90) (set 'light (!= val 0)))
((= reg 0x79) (if (!= val 0) (app-todo+ 64)))
((= reg 0x7e) (if (!= val 0) (set 'feedback 3)))
((or (= reg 0x91) (= reg 0x92)) (let ((v (!= val 0)))
(if (not (eq v alarm-tone)) {
(set 'alarm-tone v)
(app-todo+ 4)
})))
((= reg 0x17) (if (and (>= val 0) (<= val 999999) (!= val app-pin)) {
(set 'app-pin val)
(app-build-pin)
(app-todo+ 8)
}))
)
)
(defun app-run-todo ()
(if (!= app-todo 0)
(let ((td app-todo))
{
(set 'app-todo 0)
(if (= (bitwise-and td 64) 64) (ctrl-power false))
(if (= (bitwise-and td 32) 32) (toggle-lock))
(if (= (bitwise-and td 16) 16) (apply-mode))
(if (= (bitwise-and td 1) 1) (write-setting 'cruise-enabled cruise-enabled))
(if (= (bitwise-and td 2) 2) (write-setting 'auto-taillight auto-taillight))
(if (= (bitwise-and td 4) 4) (write-setting 'alarm-tone alarm-tone))
(if (= (bitwise-and td 8) 8) (write-setting 'app-pin app-pin))
}
)
)
)
(defun nb-quick (reg)
(cond
((= reg 0xb0) (get-fault))
((= reg 0xb1) (if (> alarm 0) 9 0))
((= reg 0xb2) (app-bool-word))
((= reg 0xb3) (+ (bitwise-and (rnd cur-batt) 0xFF) (shl (bitwise-and (rnd cur-batt) 0xFF) 8)))
((= reg 0xb4) (rnd cur-batt))
((or (= reg 0xb5) (= reg 0xb6)) (app-speed-01))
((= reg 0xb7) (bitwise-and cur-odo 0xFFFF))
((= reg 0xb8) (shr cur-odo 16))
((= reg 0xb9) (app-clamp16 (/ (app-trip-m) 10)))
((= reg 0xba) (to-i (secs-since app-boot-time)))
((= reg 0xbb) (app-fet-01))
((= reg 0xbe) last-alarm-code)
((= reg 0xbc) (+ (bitwise-and (rnd cur-maxkmh) 0xFF)
(shl (bitwise-and (rnd cur-maxkmh) 0xFF) 8)))
((= reg 0xbd) (app-clamp16 (* cur-vin cur-amps)))
((= reg 0xbf) (app-range-10m))
((and (>= reg 0xda) (<= reg 0xdf)) (app-word app-cpuid (- reg 0xda)))
(t 0)
)
)
(defun nb-word (reg)
(if (>= reg 0xb0)
(nb-quick reg)
(cond
((= reg 0x1a) app-ver)
((= reg 0x75) (app-workmode))
((= reg 0x7b) (cond ((= speedmode 1) 1) ((= speedmode 4) 2) (t 0)))
((= reg 0x77) (if unlock 1 0))
((= reg 0x76) (if light 1 0))
((= reg 0x7c) (if (and cruise-allow cruise-enabled) 1 0))
((= reg 0x7d) (if auto-taillight 2 0))
((or (= reg 0x24) (= reg 0x25)) (app-range-10m))
((= reg 0x3a) (to-i (secs-since app-boot-time)))
((and (>= reg 0x10) (< reg 0x17)) (app-word app-serial (- reg 0x10)))
((and (>= reg 0x17) (< reg 0x1a)) (app-word app-pin-buf (- reg 0x17)))
((= reg 0x1b) (get-fault))
((= reg 0x1c) (if (> alarm 0) 9 0))
((= reg 0x1d) (app-bool-word))
((= reg 0x1f) (app-workmode))
((= reg 0x22) (rnd cur-batt))
((= reg 0x26) (app-speed-01))
((= reg 0x29) (bitwise-and cur-odo 0xFFFF))
((= reg 0x2a) (shr cur-odo 16))
((= reg 0x2f) (app-clamp16 (/ (app-trip-m) 10)))
((= reg 0x32) (bitwise-and cur-runtime 0xFFFF))
((= reg 0x33) (shr cur-runtime 16))
((= reg 0x3e) (app-fet-01))
((= reg 0x41) (app-clamp16 (* cur-mot 10)))
((= reg 0x46) 0x32)
((or (= reg 0x47) (= reg 0x48)) (app-volt-cv))
((or (= reg 0x49) (= reg 0x53)) (app-amp-ca))
((= reg 0x65) (app-speed-01))
((or (= reg 0x66) (= reg 0x67) (= reg 0x68)) app-ver)
((= reg 0x72) (if (= speedmode 2) 1 0))
((or (= reg 0x73) (= reg 0x74)) (app-clamp16 (* cur-maxkmh 10)))
((= reg 0x7a) (if light 1 0))
((= reg 0x90) (if light 1 0))
((or (= reg 0x91) (= reg 0x92)) (if alarm-tone 1 0))
(t 0)
)
)
)
(defun nb-ack (from dst reg)
(let ((buf (array-create 10)) (crc (+ 1 from dst 0x05 reg 1)))
{
(trap {
(bufset-u16 buf 0 0x5aa5)
(bufset-u8 buf 2 1)
(bufset-u8 buf 3 from)
(bufset-u8 buf 4 dst)
(bufset-u8 buf 5 0x05)
(bufset-u8 buf 6 reg)
(bufset-u8 buf 7 1)
(setq crc (bitwise-xor crc 0xFFFF))
(bufset-u8 buf 8 (bitwise-and crc 0xFF))
(bufset-u8 buf 9 (bitwise-and (shr crc 8) 0xFF))
(uart-write buf)
})
(free buf)
}
)
)
(defun app-hold (dev reg n)
{
(if (or (< n 2) (> n 64)) (setq n 2))
(setq n (bitwise-and n 0xFE))
(if (not (and (>= n 20) levers-active))
(if (not app-pend) {
(set 'pend-dev dev) (set 'pend-reg reg) (set 'pend-n n)
(set 'app-pend true)
}
(if (not app-pend2) {
(set 'pend2-dev dev) (set 'pend2-reg reg) (set 'pend2-n n)
(set 'app-pend2 true)
}))
)
}
)
(defun app-fr-len (n) (+ n (if (= model 1) 8 9)))
(defun xm-word (reg)
(if (or (= reg 0x26) (= reg 0x65) (= reg 0xb5) (= reg 0xb6))
(app-clamp16 (* (abs cur-speed-kmh) 1000))
(nb-word reg)
)
)
(defun xm-bms-word (reg)
(cond
((and (>= reg 0x10) (< reg 0x17)) (app-word app-serial (- reg 0x10)))
((= reg 0x17) app-ver)
((or (= reg 0x18) (= reg 0x19)) (app-cap-mah))
((= reg 0x1a) 3600)
((= reg 0x20) 0x3021)
((= reg 0x30) (if (< cur-amps 0) 65 1))
((= reg 0x31) (app-clamp16 (/ (* cur-batt cur-cap) 100)))
((= reg 0x32) (rnd cur-batt))
((= reg 0x33) (app-amp-ca))
((= reg 0x34) (app-volt-cv))
((= reg 0x35) (let ((tc (bitwise-and (+ (rnd cur-fet) 20) 0xFF)))
(+ tc (shl tc 8))))
((= reg 0x3b) cur-soh)
((and (>= reg 0x40) (< reg 0x4f) (< (- reg 0x40) cur-cells))
(app-cell-mv (- reg 0x40)))
(t 0)
)
)
(defun app-frame (dev src cmd reg len)
(let ((xm (= model 1)))
(let ((p (if xm 3 4)) (n (if xm (- len 2) len)))
(if (= cmd 0x01)
(let ((want (if (> n 0) (bufget-u8 uart-buf p) 2)))
{
(if (not xm) {
(if (!= src app-dst) (set 'app-dst src))
(if (and (= reg 0xb0) (= want 52)) (set 'b0-wanted true))
})
(app-hold dev reg want)
}
)
{
(if (and (> n 0) (!= dev 0x22))
(app-write reg (if (> n 1)
(+ (bufget-u8 uart-buf p) (shl (bufget-u8 uart-buf (+ p 1)) 8))
(bufget-u8 uart-buf p)
))
)
(if (not xm) (nb-ack dev src reg))
}
)
)
)
)
(defun g2-extras (len)
(if (>= len 4)
(let ((a (bufget-u8 uart-buf 7)))
{
(if (= a 0x60) (set 'feedback 1))
(if (and (= a 0x50) (!= g2-aux 0x50) cruise-allow (not off) (not lock)) {
(set 'cruise-enabled (not cruise-enabled))
(set 'feedback 2)
(app-todo+ 1)
})
(set 'g2-aux a)
}
)
)
)
(defunret read-frame ()
{
(uart-read-bytes uart-buf 3 0)
(loopwhile (!= (bufget-u16 uart-buf 0) rx-hdr) {
(bufset-u8 uart-buf 0 (bufget-u8 uart-buf 1))
(bufset-u8 uart-buf 1 (bufget-u8 uart-buf 2))
(uart-read-bytes uart-buf 1 2)
})
(var len (bufget-u8 uart-buf 2))
(if (> len 58) (return nil))
(uart-read-bytes uart-buf (+ len rx-pre 2) 0)
(var crc len)
(looprange i 0 (+ len rx-pre) (setq crc (+ crc (bufget-u8 uart-buf i))))
(if (= (+ (bufget-u8 uart-buf (+ len rx-pre))
(shl (bufget-u8 uart-buf (+ len rx-pre 1)) 8))
(bitwise-xor crc 0xFFFF))
len
nil
)
}
)
(defun read-frames ()
(loopwhile t {
(trap
(loopwhile t
(let ((len (read-frame)))
(if (not (eq len nil))
(let ((cmd (bufget-u8 uart-buf (+ 1 rx-o)))
(dev (bufget-u8 uart-buf rx-o)))
(cond
((and (= cmd 0x61) (= rx-o 0)) {
(if (>= len 6) (adc-input 1))
(if app-enable (app-hold dev (bufget-u8 uart-buf 2)
(bufget-u8 uart-buf 3)))
})
((or (= cmd 0x61) (= cmd 0x65) (= cmd 0x64)) {
(if (>= (- len rx-sub) (if (and (= cmd 0x64) (= rx-o 1)) 7 3))
(adc-input 0))
(if (= model 3) (g2-extras len))
(if (and (= cmd 0x64)
(> (secs-since dash-tx-time) dash-tx-iv)) {
(set 'dash-tx-time (systime))
(if app-pend (send-dash-and-app) (update-dash))
})
})
((and app-enable (>= cmd 0x01) (<= cmd 0x03)
(or (= rx-o 0) (= dev 0x20) (= dev 0x22)))
(trap (app-frame dev (bufget-u8 uart-buf 0) cmd
(bufget-u8 uart-buf (+ 2 rx-o)) len)))
)
)
)
)
)
)
(sleep 0.005)
})
)
(defun combo-held(combo thr brk)
(cond
((= combo 0) (and (> brk adc-touch) (> thr adc-touch)))
((= combo 1) (and (> brk adc-touch) (<= thr adc-touch)))
((= combo 2) (and (> thr adc-touch) (<= brk adc-touch)))
((= combo 3) (and (<= brk adc-touch) (<= thr adc-touch)))
)
)
(defun combo-state-match(combo state)
(cond
((= combo 0) (= state 3))
((= combo 1) (= state 1))
((= combo 2) (= state 2))
)
)
(defun toggle-secret()
{
(set 'unlock (not unlock))
(set 'feedback 2)
(apply-mode)
}
)
(defun toggle-lock()
{
(set 'lock (not lock))
(if (and lock secret-exit-on-lock) (set 'unlock false))
(apply-mode)
(set 'feedback 1)
(if (not lock)
(stop-alarm)
)
}
)
(defun cycle-mode()
{
(cond
((= speedmode 1) (set 'speedmode 4))
((= speedmode 2) (set 'speedmode 1))
((= speedmode 4) (set 'speedmode 2))
)
(apply-mode)
}
)
(defun toggle-light()
(set 'light (not light))
)
(def lock-safety-speed (/ 0.1 3.6))
(defun gestures-allowed() (or off (<= (abs (get-speed)) button-safety-speed)))
(defun at-standstill() (or off (<= (abs (get-speed)) lock-safety-speed)))
(defun handle-button()
{
(var thr lev-thr)
(var brk lev-brk)
(cond
((and off (= presses 1))
{
(set 'off false)
(set 'feedback 1)
(set 'unlock false)
(boot-state)
(apply-mode)
(stats-reset)
}
)
((and unlock
(if secret-off-requires-lock lock (not lock))
(> secret-off-presses 0)
(= presses secret-off-presses)
(combo-held secret-off-combo thr brk))
(toggle-secret)
)
((and secret-enabled
(> secret-presses 0)
(= presses secret-presses)
(combo-held secret-combo thr brk)
(or (not secret-requires-lock) lock))
(toggle-secret)
)
((and (> lock-presses 0)
(= presses lock-presses)
(combo-held lock-combo thr brk))
(if (at-standstill) (toggle-lock))
)
((and (if mode-requires-lock lock (not lock))
(> mode-presses 0)
(= presses mode-presses)
(combo-held mode-combo thr brk))
(cycle-mode)
)
((and (if light-requires-lock lock (not lock))
(> light-presses 0)
(= presses light-presses)
(combo-held light-combo thr brk))
(toggle-light)
)
(lock (set 'feedback 1))
)
}
)
(defun handle-lever-gestures()
{
(var thr lev-thr)
(var brk lev-brk)
(var state (+ (if (> brk adc-touch) 1 0) (if (> thr adc-touch) 2 0)))
(if (!= state lever-state) {
(set 'lever-state state)
(set 'lever-since (systime))
})
(if (= state 0) (set 'lever-armed true))
(if (and lever-armed (> state 0) (> (secs-since lever-since) 0.5))
(cond
((and unlock (= secret-off-presses 0)
(if secret-off-requires-lock lock (not lock))
(combo-state-match secret-off-combo state))
{
(set 'lever-armed false)
(toggle-secret)
}
)
((and secret-enabled
(= secret-presses 0)
(combo-state-match secret-combo state)
(or (not secret-requires-lock) lock))
{
(set 'lever-armed false)
(toggle-secret)
}
)
((and (if mode-requires-lock lock (not lock)) (= mode-presses 0) (combo-state-match mode-combo state))
{
(set 'lever-armed false)
(cycle-mode)
}
)
((and (if light-requires-lock lock (not lock)) (= light-presses 0) (combo-state-match light-combo state))
{
(set 'lever-armed false)
(toggle-light)
}
)
)
)
}
)
(defun handle-holding-button()
{
(if (and (not lock) (not off))
{
(set 'light false)
(set 'feedback 1)
(set 'unlock false)
(apply-mode)
(set 'off true)
}
)
}
)
(defun reset-button()
{
(set 'press-time (systime))
(set 'presses 0)
}
)
(defun apply-mode()
(if (not unlock)
(cond
((= speedmode 1) (configure-speed drive-speed drive-watts drive-current drive-fw drive-om))
((= speedmode 2) (configure-speed eco-speed eco-watts eco-current eco-fw eco-om))
((= speedmode 4) (configure-speed sport-speed sport-watts sport-current sport-fw sport-om))
)
(cond
((= speedmode 1) (configure-speed secret-drive-speed secret-drive-watts secret-drive-current secret-drive-fw secret-drive-om))
((= speedmode 2) (configure-speed secret-eco-speed secret-eco-watts secret-eco-current secret-eco-fw secret-eco-om))
((= speedmode 4) (configure-speed secret-sport-speed secret-sport-watts secret-sport-current secret-sport-fw secret-sport-om))
)
)
)
(defun configure-speed(speed watts current fw om)
{
(if apply-speed (set-param 'max-speed speed))
(if apply-watts (set-param 'l-watt-max watts))
(if apply-current (set-param 'l-current-max-scale current))
(if apply-fw (set-param 'foc-fw-current-max fw))
(if apply-om (set-param 'foc-overmod-factor om))
}
)
(defun set-param(param value)
{
(conf-set param value)
(loopforeach id (can-list-devs)
(looprange i 0 5 {
(if (eq (rcode-run id 0.1 `(conf-set (quote ,param) ,value)) t) (break t))
false
})
)
}
)
(defun start-alarm()
(if (= alarm 0)
{
(set 'alarm 1)
(set 'last-alarm-code 9)
(set 'alarm-time (systime))
(print "Alarm started")
}
)
)
(defun stop-alarm()
(if (> alarm 0)
{
(set 'alarm 0)
(set-brake-rel 0)
(stop-tone)
(print "Alarm stopped")
}
)
)
(defun stop-current()
{
(set-current-rel 0)
(loopforeach id (can-devs)
(rcode-run-noret id '(set-current-rel 0))
)
}
)
(defun handle-lock(speed)
{
(if lock
{
(var gyro (get-gyro))
(cond
((or (> (abs (ix gyro 0)) alarm-gyro-threshold) (> (abs (ix gyro 1)) alarm-gyro-threshold) (> (abs (ix gyro 2)) alarm-gyro-threshold))
(start-alarm)
)
((> speed alarm-speed-threshold)
(start-alarm)
)
((> (secs-since alarm-time) 3)
(stop-alarm)
)
)
}
(stop-alarm)
)
(if lock
{
(set-current-rel 0)
(if (and (> alarm 0) (> speed 0.0))
(set-brake-rel 1)
(set-brake-rel 0)
)
}
)
(cond
((= alarm 2)
{
(if alarm-tone
(play-tone 0 4000 alarm-voltage)
)
(set 'feedback 1)
}
)
((= alarm 3)
{
(if alarm-tone
(play-tone 2 7000 alarm-voltage)
)
(set 'feedback 1)
}
)
((= alarm 6)
{
(if alarm-tone
(play-tone 1 2000 alarm-voltage)
)
(set 'feedback 1)
}
)
((= alarm 8)
{
(if alarm-tone
(stop-tone)
)
(set 'feedback 1)
(set 'alarm 1)
}
)
)
(if (> alarm 0)
(set 'alarm (+ alarm 1))
)
}
)
(defun play-tone(channel freq voltage)
{
(foc-play-tone channel freq voltage)
(loopforeach id (can-devs)
(rcode-run-noret id `(foc-play-tone ,channel ,freq ,voltage))
)
}
)
(defun stop-tone()
{
(foc-play-stop)
(loopforeach id (can-devs)
(rcode-run-noret id '(foc-play-stop))
)
}
)
(defun can-devs ()
{
(if (> (secs-since can-ids-time) 0.5) {
(set 'can-ids-time (systime))
(set 'can-ids (can-list-devs))
})
can-ids
}
)
(defun check-slip ()
(if (<= lev-brk adc-touch)
(let ((r (abs (get-rpm))))
(let ((lo r) (hi r))
{
(trap (loopforeach i (can-devs)
(let ((v (abs (canget-rpm i))))
{ (if (< v lo) (setq lo v)) (if (> v hi) (setq hi v)) })))
(if (and (> lo 0) (> (- hi lo) slip-erpm)) (set 'slip-time (systime)))
}
)
)
)
)
(defun wheel-slip ()
(if (and (> slip-time 0) (< (secs-since slip-time) slip-hold)) 1 0))
(defun get-lowest-speed()
{
(var speed (get-speed))
(trap
(loopforeach i (can-devs)
(let ((can-speed (canget-speed i)))
(if (< can-speed speed) (set 'speed can-speed))
)
)
)
speed
}
)
(defun gyro-live (g)
(and (eq (type-of g) 'type-list) (= (length g) 3)
(or (> (abs (ix g 0)) 0) (> (abs (ix g 1)) 0) (> (abs (ix g 2)) 0)))
)
(defunret get-gyro()
{
(var g (if (< gyro-src 0) (get-imu-gyro) (rcode-run gyro-src 0.5 '(get-imu-gyro))))
(if (gyro-live g) (return g))
(if (< (secs-since gyro-probe) 10.0) (return '(0.0 0.0 0.0)))
(set 'gyro-probe (systime))
(set 'gyro-src -1)
(setq g (get-imu-gyro))
(if (gyro-live g) (return g))
(loopforeach i (can-devs)
(let ((c (rcode-run i 0.5 '(get-imu-gyro))))
(if (gyro-live c) {
(set 'gyro-src i)
(return c)
})
)
)
'(0.0 0.0 0.0)
}
)
(defun read-button-pin()
{
(var sample-num 3)
(var sample-sum 0)
(looprange i 0 sample-num {
(sleep 0.02)
(setq sample-sum (+ sample-sum (gpio-read 'pin-rx)))
})
(= (if (> sample-sum (/ sample-num 2)) 1 0) 0)
}
)
(defun button-logic()
{
(loopwhile t
{
(var button-state (read-button-pin))
(if (and button-state (not last-button-state))
{
(set 'presses (+ presses 1))
(set 'press-time (systime))
}
)
(set 'last-button-state button-state)
(trap {
(set 'lev-thr (get-adc-decoded 0))
(set 'lev-brk (get-adc-decoded 1))
(button-apply button-state)
(if (and (not off) (gestures-allowed)) (handle-lever-gestures))
(handle-features)
})
}
)
}
)
(defun button-apply(button)
{
(var time-passed (- (systime) press-time))
(if (> time-passed 3000)
(if button
(if (> time-passed 6000)
{
(if (at-standstill)
(handle-holding-button)
)
(reset-button)
}
)
(if (> presses 0)
{
(if (gestures-allowed)
(handle-button)
)
(reset-button)
}
)
)
)
}
)
(defun main () {
(load-settings)
(event-register-handler (spawn event-handler))
(event-enable 'event-data-rx)
(if (= model 2) {
(start-code-server)
} {
(boot-state)
(if rear-light-enable {
(pwm-start 200 0)
(set 'pwm-started true)
})
(uart-start 115200 'half-duplex)
(gpio-configure 'pin-rx 'pin-mode-in-pu)
(def uart-buf (array-create 64))
(def app-serial (array-create 14))
(def app-cpuid (array-create 12))
(def app-pin-buf (array-create 6))
(def app-cells (array-create 30))
(if (!= model 1)
{
(def app-f-b0 (array-create 61))
(def app-f-b4 (array-create 15))
(def app-f-7b (array-create 15))
(def app-f-1a (array-create 11))
(def app-f-25 (array-create 11))
(def app-f-3b (array-create 11))
(def app-f-75 (array-create 11))
(def app-f-da (array-create 21))
(def app-f-33 (array-create 13))
(def app-f-35 (array-create 11))
(def app-f-31 (array-create 11))
(def app-f-40 (array-create 39))
}
)
(set 'cur-cells (let ((n (conf-get 'si-battery-cells))) (if (> n 0) n 10)))
(set 'cur-wh-tot (* 0.85 (conf-get 'si-battery-ah) (* 3.7 (conf-get 'si-battery-cells))))
(set 'cur-cap (app-clamp16 (* (conf-get 'si-battery-ah) 1000)))
(set 'last-rx (systime))
(set 'app-cache-time (systime))
(set 'app-slow-time (systime))
(set 'dash-tx-time 0)
(set 'press-time (systime))
(set 'alarm-time (systime))
(set 'lever-since (systime))
(set 'blink-since (systime))
(set 'cruise-since (systime))
(set 'cruise-shown-time (systime))
(set 'calib-since (systime))
(app-build-serial)
(app-build-pin)
(if (!= model 1) {
(build-app-frame app-f-1a 0x1a 2)
(build-app-frame app-f-da 0xda 12)
(build-app-frame app-f-3b 0x3b 2)
(build-app-frame app-f-b0 0xb0 52)
})
(set 'app-boot-time (systime))
(if (= model 1) {
(define tx-frame (array-create 14))
(bufset-u16 tx-frame 0 0x55AA)
(bufset-u16 tx-frame 2 0x0821)
(bufset-u16 tx-frame 4 0x6400)
(set 'rx-hdr 0x55aa)
(set 'rx-pre 1)
(set 'rx-o 0)
(set 'rx-sub 2)
(set 'tx-base 6)
(set 'thr-idx 4)
(set 'brk-idx 5)
} {
(define tx-frame (array-create (if (= model 3) 17 15)))
(bufset-u16 tx-frame 0 0x5AA5)
(bufset-u8 tx-frame 2 (if (= model 3) 0x08 0x06))
(bufset-u16 tx-frame 3 0x2021)
(bufset-u16 tx-frame 5 0x6400)
(if (= model 3) {
(bufset-u8 tx-frame 13 0x04)
(bufset-u8 tx-frame 14 0x91)
})
(set 'rx-hdr 0x5aa5)
(set 'rx-pre 4)
(set 'tx-base 7)
(set 'thr-idx 5)
(set 'brk-idx 6)
})
(looprange i 2 tx-base (set 'tx-hdr-sum (+ tx-hdr-sum (bufget-u8 tx-frame i))))
(if (!= model 1)
(let ((dl (buflen tx-frame)))
{
(def combo11 (array-create (+ dl 11)))
(def combo13 (array-create (+ dl 13)))
(def combo15 (array-create (+ dl 15)))
(def combo21 (array-create (+ dl 21)))
(def combo39 (array-create (+ dl 39)))
(def combo61 (array-create (+ dl 61)))
}
)
)
(apply-software-adc)
(apply-dash-power)
(set 'cur-batt (* (get-batt) 100))
(spawn 500 read-frames)
(apply-mode)
(button-logic)
})
})
@const-end
(def img-ok true)
(set 'img-ok (image-save))
(if (not img-ok) (print "image-save failed - script too big, will not boot"))
(main)
